// playground/react-playground/app/data/md/vue2-guide.ts
export default [
  "# Ve2 接入指南",
  "",
  "本文面向 Vue 2 项目，即 Vue 2 + TypeScript + CodeMirror 6 的接入方式。目标是让业务项目接入一个与 Markora Vue 2 playground 同等质量的编辑器：支持富 Markdown 编辑、源码模式、预览模式、HTML/CSS 输出、插件开关、slash commands、附件上传、选区工具栏、目录、主题切换和本地持久化。",
  "",
  "## 1. Vue 2 接入结论",
  "",
  "| 项目         | 建议                                                                         |",
  "| ------------ | ---------------------------------------------------------------------------- |",
  "| 接入方式     | 直接在 Vue 2 组件中创建 CodeMirror `EditorView`。                            |",
  "| 组件生命周期 | `mounted()` 创建或重建，`beforeDestroy()` 销毁。                             |",
  "| 文档状态     | Vue state 保存 Markdown 原文，CodeMirror 只作为编辑视图。                    |",
  "| 预览状态     | 使用 `preview()` + `generateCSS()` 生成 HTML/CSS。                           |",
  "| 附件上传     | 在 `attachments.uploader` 中接入业务上传接口。                               |",
  "| 目录         | 编辑态可用 `toc.onTocChange`，预览态可用 `extractPreviewTocFromMarkdown()`。 |",
  "",
  "## 2. 安装依赖",
  "",
  "```shell",
  "npm install @refinex/markora",
  "```",
  "",
  "下面的 HTML/CSS 输出面板示例会用到 `@codemirror/lang-html`、`@codemirror/lang-css` 和 `@uiw/codemirror-theme-github`；只有保留该面板时才需要按需安装。",
  "",
  "Vue 2 项目还需要自己的构建环境，例如 `vue@2`、`vue-template-compiler`、`@vue/cli-service`、`@vue/cli-plugin-typescript`。Markora 不提供 Vue 2 adapter，也不要求额外 adapter。",
  "",
  "## 3. 模板结构",
  "",
  "```vue",
  "<template>",
  '  <section class="markora-vue2-shell">',
  '    <header class="markora-toolbar">',
  '      <button type="button" @click="mode = \'live\'">编辑</button>',
  '      <button type="button" @click="mode = \'code\'">源码</button>',
  '      <button type="button" @click="mode = \'view\'">预览</button>',
  '      <button type="button" @click="mode = \'output\'">输出</button>',
  "    </header>",
  "",
  '    <div v-if="mode === \'view\'" ref="previewHost" class="markora-preview-host">',
  '      <div v-html="previewOutput.html" />',
  "",
  '      <aside v-if="config.features.tableOfContents" class="markora-preview-toc">',
  "        <button",
  '          v-for="item in previewToc"',
  '          :key="item.id"',
  '          type="button"',
  '          :data-level="item.level"',
  '          :class="{ active: item.active }"',
  '          @click="jumpToc(item)"',
  "        >",
  "          {{ item.text }}",
  "        </button>",
  "      </aside>",
  "    </div>",
  "",
  '    <div v-else-if="mode === \'output\'" class="markora-output-grid">',
  '      <div ref="htmlOutputHost" />',
  '      <div ref="cssOutputHost" />',
  "    </div>",
  "",
  '    <div v-else ref="editorHost" class="markora-editor-host" />',
  "  </section>",
  "</template>",
  "```",
  "",
  "```css",
  ".markora-vue2-shell {",
  "  display: flex;",
  "  flex-direction: column;",
  "  height: 100vh;",
  "}",
  "",
  ".markora-editor-host,",
  ".markora-preview-host,",
  ".markora-output-grid {",
  "  flex: 1;",
  "  min-height: 0;",
  "  overflow: auto;",
  "}",
  "",
  ".markora-output-grid {",
  "  display: grid;",
  "  grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);",
  "}",
  "```",
  "",
  "## 4. 配置模型",
  "",
  "```ts",
  'import { allPlugins } from "@refinex/markora/plugins";',
  "",
  "export type PluginConfig = Record<string, boolean>;",
  "",
  "export type PlaygroundConfig = {",
  '  locale: "zh-CN" | "en-US";',
  "  editor: {",
  "    baseStyles: boolean;",
  "    defaultKeybindings: boolean;",
  "    history: boolean;",
  "    indentWithTab: boolean;",
  "    highlightActiveLine: boolean;",
  "    lineWrapping: boolean;",
  "  };",
  "  preview: {",
  "    includeBase: boolean;",
  "    sanitize: boolean;",
  "  };",
  "  features: {",
  "    slashCommands: boolean;",
  "    attachments: boolean;",
  "    pasteDropUploads: boolean;",
  "    selectionToolbar: boolean;",
  "    tableOfContents: boolean;",
  "  };",
  "  plugins: PluginConfig;",
  "};",
  "",
  "export function createDefaultPluginConfig(): PluginConfig {",
  "  return Object.fromEntries(allPlugins.map((plugin) => [plugin.name.toLowerCase(), true]));",
  "}",
  "",
  "export function getActivePlugins(pluginConfig: PluginConfig) {",
  "  return allPlugins.filter((plugin) => pluginConfig[plugin.name.toLowerCase()] !== false);",
  "}",
  "",
  "export const defaultConfig: PlaygroundConfig = {",
  '  locale: "zh-CN",',
  "  editor: {",
  "    baseStyles: true,",
  "    defaultKeybindings: true,",
  "    history: true,",
  "    indentWithTab: true,",
  "    highlightActiveLine: true,",
  "    lineWrapping: true,",
  "  },",
  "  preview: {",
  "    includeBase: true,",
  "    sanitize: true,",
  "  },",
  "  features: {",
  "    slashCommands: true,",
  "    attachments: true,",
  "    pasteDropUploads: true,",
  "    selectionToolbar: true,",
  "    tableOfContents: true,",
  "  },",
  "  plugins: createDefaultPluginConfig(),",
  "};",
  "```",
  "",
  "## 5. 完整组件脚本",
  "",
  "```ts",
  'import Vue from "vue";',
  'import { html } from "@codemirror/lang-html";',
  'import { css } from "@codemirror/lang-css";',
  'import { githubDark, githubLight } from "@uiw/codemirror-theme-github";',
  'import type { MarkoraAttachmentUploadContext, MarkoraNode, MarkoraTocItem } from "@refinex/markora/editor";',
  'import { EditorState, EditorView, markora, ThemeEnum } from "@refinex/markora/editor";',
  'import { extractPreviewTocFromMarkdown, generateCSS, preview } from "@refinex/markora/preview";',
  'import { defaultConfig, getActivePlugins } from "./playground-config";',
  "",
  'type Mode = "live" | "code" | "view" | "output";',
  "",
  "export default Vue.extend({",
  '  name: "MarkoraVue2Editor",',
  "",
  "  data() {",
  "    return {",
  '      mode: "live" as Mode,',
  '      theme: "light" as "light" | "dark",',
  '      content: "# Hello, Markora",',
  "      config: defaultConfig,",
  "      editorView: null as EditorView | null,",
  "      htmlView: null as EditorView | null,",
  "      cssView: null as EditorView | null,",
  "      previewStyleElement: null as HTMLStyleElement | null,",
  '      previewOutput: { html: "", css: "" },',
  "      previewToc: [] as MarkoraTocItem[],",
  "      objectUrls: [] as string[],",
  "      internalUpdate: false,",
  "    };",
  "  },",
  "",
  "  mounted() {",
  "    // Vue 2 组件挂载后，DOM ref 才可用于创建 EditorView。",
  "    this.rebuildForMode();",
  "  },",
  "",
  "  beforeDestroy() {",
  "    // 销毁所有 CodeMirror 视图和临时 URL，避免内存泄漏。",
  "    this.destroyViews();",
  "    this.revokeObjectUrls();",
  "  },",
  "",
  "  watch: {",
  "    mode() {",
  "      this.rebuildForMode();",
  "    },",
  "    theme() {",
  "      this.rebuildForMode();",
  "    },",
  "    config: {",
  "      deep: true,",
  "      handler() {",
  "        this.rebuildForMode();",
  "      },",
  "    },",
  "    content(next: string) {",
  "      // 外部状态变更时同步到 CodeMirror，但避免由 CodeMirror 输入触发死循环。",
  "      if (!this.editorView || next === this.editorView.state.doc.toString()) return;",
  "",
  "      this.internalUpdate = true;",
  "      this.editorView.dispatch({",
  "        changes: {",
  "          from: 0,",
  "          to: this.editorView.state.doc.length,",
  "          insert: next,",
  "        },",
  "      });",
  "      this.internalUpdate = false;",
  "    },",
  "  },",
  "",
  "  methods: {",
  "    cmTheme() {",
  '      return this.theme === "dark" ? githubDark : githubLight;',
  "    },",
  "",
  "    markoraTheme() {",
  '      return this.theme === "dark" ? ThemeEnum.DARK : ThemeEnum.LIGHT;',
  "    },",
  "",
  "    async uploader(file: File) {",
  "      // playground 可用 blob URL 演示；生产环境必须改成真实上传接口。",
  "      const url = URL.createObjectURL(file);",
  "      this.objectUrls.push(url);",
  "      return {",
  "        url,",
  "        name: file.name,",
  "        mimeType: file.type,",
  "      };",
  "    },",
  "",
  "    rebuildForMode() {",
  "      this.$nextTick(() => {",
  "        this.destroyViews();",
  "",
  '        if (this.mode === "view" || this.mode === "output") {',
  "          this.renderPreview();",
  "          return;",
  "        }",
  "",
  "        this.createEditorView();",
  "      });",
  "    },",
  "",
  "    createEditorView() {",
  "      const parent = this.$refs.editorHost as HTMLElement | undefined;",
  "      if (!parent) return;",
  "",
  "      const updateListener = EditorView.updateListener.of((update) => {",
  "        if (!update.docChanged || this.internalUpdate) return;",
  "        this.content = update.state.doc.toString();",
  "      });",
  "",
  "      this.editorView = new EditorView({",
  "        parent,",
  "        state: EditorState.create({",
  "          doc: this.content,",
  "          extensions: [",
  "            this.cmTheme(),",
  "            markora({",
  "              theme: this.markoraTheme(),",
  "              locale: this.config.locale,",
  "              baseStyles: this.config.editor.baseStyles,",
  "              plugins: getActivePlugins(this.config.plugins),",
  '              disableViewPlugin: this.mode === "code",',
  "              defaultKeybindings: this.config.editor.defaultKeybindings,",
  "              history: this.config.editor.history,",
  "              indentWithTab: this.config.editor.indentWithTab,",
  "              highlightActiveLine: this.config.editor.highlightActiveLine,",
  "              lineWrapping: this.config.editor.lineWrapping,",
  "              slashCommands: {",
  "                enabled: this.config.features.slashCommands,",
  "              },",
  "              selectionToolbar: {",
  "                enabled: this.config.features.selectionToolbar,",
  "              },",
  "              toc: {",
  '                enabled: this.mode === "live" && this.config.features.tableOfContents,',
  '                storageKey: "markora-vue2:toc",',
  "                onTocChange: (items: MarkoraTocItem[]) => {",
  "                  this.previewToc = items;",
  "                },",
  "              },",
  "              attachments: {",
  "                enabled: this.config.features.attachments,",
  "                uploader: this.config.features.attachments ? this.uploader : undefined,",
  "                enablePaste: this.config.features.pasteDropUploads,",
  "                enableDrop: this.config.features.pasteDropUploads,",
  "                accept: {",
  '                  image: ["image/*"],',
  '                  video: ["video/*"],',
  '                  audio: ["audio/*"],',
  '                  file: ["*/*"],',
  "                },",
  "              },",
  "              onNodesChange: (nodes: MarkoraNode[]) => {",
  '                this.$emit("nodes-change", nodes);',
  "              },",
  "            }),",
  "            updateListener,",
  "          ],",
  "        }),",
  "      });",
  "    },",
  "",
  "    async renderPreview() {",
  "      const plugins = getActivePlugins(this.config.plugins);",
  "      const syntaxTheme = this.cmTheme();",
  "",
  "      const htmlOutput = await preview(this.content, {",
  "        theme: this.markoraTheme(),",
  "        plugins,",
  "        markdown: [],",
  "        syntaxTheme,",
  "        sanitize: this.config.preview.sanitize,",
  '        wrapperTag: "div",',
  '        wrapperClass: "markora-preview vue2-preview",',
  "      });",
  "",
  "      const cssOutput = generateCSS({",
  "        theme: this.markoraTheme(),",
  "        plugins,",
  '        wrapperClass: "markora-preview",',
  "        includeBase: this.config.preview.includeBase,",
  "        syntaxTheme,",
  "      });",
  "",
  "      this.previewOutput = { html: htmlOutput, css: cssOutput };",
  "      this.previewToc = extractPreviewTocFromMarkdown(this.content);",
  "",
  "      this.$nextTick(() => {",
  '        if (this.mode === "view") this.updatePreviewStyles();',
  '        if (this.mode === "output") this.createOutputViews();',
  "      });",
  "    },",
  "",
  "    updatePreviewStyles() {",
  "      const previewHost = this.$refs.previewHost as HTMLElement | undefined;",
  "      if (!previewHost) return;",
  "",
  "      if (!this.previewStyleElement) {",
  '        this.previewStyleElement = document.createElement("style");',
  "        previewHost.prepend(this.previewStyleElement);",
  "      }",
  "",
  "      this.previewStyleElement.textContent = this.previewOutput.css;",
  "    },",
  "",
  "    createOutputViews() {",
  "      const htmlParent = this.$refs.htmlOutputHost as HTMLElement | undefined;",
  "      const cssParent = this.$refs.cssOutputHost as HTMLElement | undefined;",
  "      if (!htmlParent || !cssParent) return;",
  "",
  "      this.htmlView = new EditorView({",
  "        parent: htmlParent,",
  "        state: EditorState.create({",
  "          doc: this.previewOutput.html,",
  "          extensions: [this.cmTheme(), html(), EditorView.lineWrapping, EditorState.readOnly.of(true)],",
  "        }),",
  "      });",
  "",
  "      this.cssView = new EditorView({",
  "        parent: cssParent,",
  "        state: EditorState.create({",
  "          doc: this.previewOutput.css,",
  "          extensions: [this.cmTheme(), css(), EditorView.lineWrapping, EditorState.readOnly.of(true)],",
  "        }),",
  "      });",
  "    },",
  "",
  "    jumpToc(item: MarkoraTocItem) {",
  '      if (this.mode === "view") {',
  "        const host = this.$refs.previewHost as HTMLElement | undefined;",
  "        const target = host?.querySelector(`#${CSS.escape(item.id)}`) as HTMLElement | null;",
  '        target?.scrollIntoView({ block: "start" });',
  "        return;",
  "      }",
  "",
  '      if (this.editorView && typeof item.from === "number") {',
  "        this.editorView.dispatch({",
  "          selection: { anchor: item.from },",
  '          effects: EditorView.scrollIntoView(item.from, { y: "start" }),',
  "        });",
  "        this.editorView.focus();",
  "      }",
  "    },",
  "",
  "    destroyViews() {",
  "      this.editorView?.destroy();",
  "      this.htmlView?.destroy();",
  "      this.cssView?.destroy();",
  "      this.editorView = null;",
  "      this.htmlView = null;",
  "      this.cssView = null;",
  "",
  "      if (this.previewStyleElement) {",
  "        this.previewStyleElement.remove();",
  "        this.previewStyleElement = null;",
  "      }",
  "    },",
  "",
  "    revokeObjectUrls() {",
  "      for (const url of this.objectUrls) {",
  "        URL.revokeObjectURL(url);",
  "      }",
  "      this.objectUrls = [];",
  "    },",
  "  },",
  "});",
  "```",
  "",
  "## 6. Markora 配置速查",
  "",
  "| 配置                       | 默认值           | Vue 2 建议                                                                       |",
  "| -------------------------- | ---------------- | -------------------------------------------------------------------------------- |",
  "| `theme`                    | `ThemeEnum.AUTO` | 跟随应用主题明确传 `ThemeEnum.LIGHT/DARK`，避免 Vue 2 主题状态和系统主题不一致。 |",
  '| `locale`                   | `"zh-CN"`        | 中文应用保持默认，英文应用传 `"en-US"`。                                         |',
  "| `baseStyles`               | `true`           | 初次接入保持开启。                                                               |",
  "| `plugins`                  | `[]`             | 传 `getActivePlugins(config.plugins)`，支持插件开关。                            |",
  '| `disableViewPlugin`        | `false`          | `mode === "code"` 时设为 `true`。                                                |',
  "| `defaultKeybindings`       | `true`           | 保持开启。                                                                       |",
  "| `history`                  | `true`           | 保持开启。                                                                       |",
  "| `indentWithTab`            | `true`           | 保持开启。                                                                       |",
  "| `highlightActiveLine`      | `true`           | 源码模式有用。                                                                   |",
  "| `lineWrapping`             | `true`           | 文档编辑建议开启。                                                               |",
  "| `slashCommands.enabled`    | `true`           | 通过配置开关控制。                                                               |",
  "| `selectionToolbar.enabled` | `true`           | 富文本体验建议开启。                                                             |",
  "| `toc.enabled`              | `true`           | 内置面板或自定义侧栏二选一。                                                     |",
  "| `attachments.enabled`      | `false`          | 有 uploader 后再开启。                                                           |",
  "",
  "## 7. 附件上传接入",
  "",
  "Vue 2 接入时，附件上传要明确区分 Markora 与业务后端职责。",
  "",
  "| 项目     | Markora 负责                            | 业务负责                          |",
  "| -------- | --------------------------------------- | --------------------------------- |",
  "| 文件来源 | slash 选择、paste、drop。               | 决定是否开启 paste/drop。         |",
  "| 类型判断 | 根据 MIME 判断 image/video/audio/file。 | 限制业务允许的 MIME、后缀、大小。 |",
  "| 上传过程 | 插入上传中标记，调用 `uploader`。       | 上传到后端/OSS/S3/MinIO/CDN。     |",
  "| 成功结果 | 把结果替换成 Markdown/HTML。            | 返回最终可访问 URL。              |",
  "| 失败结果 | 插入 Upload failed 标记。               | 抛出错误并记录日志。              |",
  "",
  "```ts",
  "async function productionUploader(file: File, context: MarkoraAttachmentUploadContext) {",
  "  if (file.size > 20 * 1024 * 1024) {",
  '    throw new Error("File is larger than 20MB");',
  "  }",
  "",
  "  const form = new FormData();",
  '  form.append("file", file);',
  '  form.append("kind", context.kind);',
  '  form.append("source", context.source);',
  "",
  '  const response = await fetch("/api/uploads", {',
  '    method: "POST",',
  "    body: form,",
  "  });",
  "",
  "  if (!response.ok) {",
  '    throw new Error("Upload failed");',
  "  }",
  "",
  "  return response.json();",
  "}",
  "```",
  "",
  "## 8. Preview 与输出模式",
  "",
  "| API                                       | 作用                            | Vue 2 使用方式                               |",
  "| ----------------------------------------- | ------------------------------- | -------------------------------------------- |",
  "| `preview(markdown, config)`               | 生成 HTML 字符串。              | 预览模式和发布前调用。                       |",
  "| `generateCSS(config)`                     | 生成和插件/主题一致的 CSS。     | 插入 `<style>` 或输出面板。                  |",
  "| `extractPreviewTocFromMarkdown(markdown)` | 从 Markdown 生成 preview 目录。 | 预览模式使用，因为此时可能没有 editor view。 |",
  "",
  "关键要求：`preview()` 和 `generateCSS()` 必须使用同一组 `plugins`、`theme`、`syntaxTheme`，否则 HTML 与 CSS 会不匹配。",
  "",
  "## 9. 插件体系",
  "",
  "Vue 2 不需要特殊插件写法。自定义插件仍然继承 `MarkoraPlugin`：",
  "",
  "```ts",
  'import type { DecorationContext } from "@refinex/markora/editor";',
  'import { MarkoraPlugin } from "@refinex/markora/editor";',
  "",
  "export class AuditPlugin extends MarkoraPlugin {",
  '  readonly name = "audit";',
  '  readonly version = "1.0.0";',
  "",
  "  buildDecorations(ctx: DecorationContext): void {",
  "    // 读取 ctx.view.state.doc。",
  "    // 向 ctx.decorations 追加 Decoration.range(...)。",
  "  }",
  "}",
  "```",
  "",
  "| 插件方法              | 用途                   |",
  "| --------------------- | ---------------------- |",
  "| `getExtensions()`     | 添加 CodeMirror 扩展。 |",
  "| `getMarkdownConfig()` | 添加 Markdown 语法。   |",
  "| `getKeymap()`         | 添加快捷键。           |",
  "| `buildDecorations()`  | 编辑态 decoration。    |",
  "| `renderToHTML()`      | 静态预览 HTML。        |",
  "| `getPreviewStyles()`  | 静态预览 CSS。         |",
  "",
  "## 10. 持久化与版本升级",
  "",
  "Vue 2 playground 的策略是固定默认文档 id，并通过 `STORAGE_VERSION` 刷新默认文档，同时保留用户自建文档。",
  "",
  "| 字段                   | 作用                 |",
  "| ---------------------- | -------------------- |",
  "| `STORAGE_CONTENTS_KEY` | 保存文档数组。       |",
  "| `STORAGE_CURRENT_KEY`  | 保存当前文档索引。   |",
  "| `STORAGE_VERSION_KEY`  | 保存默认文档版本。   |",
  "| `STORAGE_VERSION`      | 默认文档变更时递增。 |",
  "",
  "生产系统建议保存 Markdown 原文和业务元数据，不保存 CodeMirror 内部状态。",
  "",
  "## 11. 验收清单",
  "",
  "- 编辑、源码、预览、输出模式均可切换。",
  "- Vue 2 state 与 CodeMirror doc 不会互相覆盖。",
  "- 组件销毁后 `EditorView.destroy()` 已执行。",
  "- 附件上传成功会插入图片、音视频或文件链接。",
  "- 附件上传失败会留下用户可见失败标记。",
  "- paste/drop 与页面其他上传区域没有事件冲突。",
  "- `preview()` 与 `generateCSS()` 使用同一组插件和主题。",
  "- TOC 在编辑态和预览态都能跳转。",
  "- 默认文档升级能保留用户自建文档。",
].join("\n");

// playground/react-playground/app/data/md/react-guide.ts
export default [
  "# React 接入指南",
  "",
  "本文面向 React 项目，目标是接入一个与 Markora React playground 同等质量的编辑器：支持富 Markdown 编辑、源码模式、预览模式、HTML/CSS 输出、插件开关、slash commands、附件上传、选区工具栏、主题切换、本地持久化和节点调试。",
  "",
  "React playground 使用 `@uiw/react-codemirror` 封装 CodeMirror 生命周期。你也可以手动创建 `EditorView`，但大多数 React 项目使用 `@uiw/react-codemirror` 会更直接。",
  "",
  "## 1. React 接入结论",
  "",
  "| 项目     | 建议                                                                      |",
  "| -------- | ------------------------------------------------------------------------- |",
  "| 接入方式 | 使用 `@uiw/react-codemirror` 渲染编辑器。                                 |",
  "| 状态同步 | React state 保存 Markdown 原文，`onChange` 更新当前文档。                 |",
  "| 扩展管理 | 用 `useMemo` 生成 Markora extensions，避免每次输入重建。                  |",
  "| 预览     | 用 `useEffect` 在 view/output 模式下调用 `preview()` 和 `generateCSS()`。 |",
  "| 附件上传 | 用 `useCallback` 提供稳定 uploader。                                      |",
  "| 资源清理 | 在 `useEffect` cleanup 中释放 `blob:` URL。                               |",
  "",
  "## 2. 安装依赖",
  "",
  "```shell",
  "npm install @refinex/markora",
  "npm install @uiw/react-codemirror",
  "```",
  "",
  "下面的 HTML/CSS 输出面板示例会用到 `@codemirror/lang-html`、`@codemirror/lang-css` 和 `@uiw/codemirror-theme-github`；只有保留该面板时才需要按需安装。",
  "",
  "Next.js App Router 中，编辑器组件必须是 client component：",
  "",
  "```tsx",
  '"use client";',
  "```",
  "",
  "## 3. 类型与默认配置",
  "",
  "```tsx",
  'import { useCallback, useEffect, useMemo, useRef, useState } from "react";',
  'import CodeMirror, { ReactCodeMirrorRef } from "@uiw/react-codemirror";',
  'import { githubDark, githubLight } from "@uiw/codemirror-theme-github";',
  'import { html } from "@codemirror/lang-html";',
  'import { css } from "@codemirror/lang-css";',
  'import { EditorView, Extension, markora, MarkoraNode, MarkoraPlugin, ThemeEnum } from "@refinex/markora/editor";',
  'import { allPlugins } from "@refinex/markora/plugins";',
  'import { generateCSS, preview } from "@refinex/markora/preview";',
  "",
  "type Content = {",
  "  id: string;",
  "  title: string;",
  "  content: string;",
  "};",
  "",
  'type Mode = "live" | "view" | "code" | "output";',
  "type PluginConfig = Record<string, boolean>;",
  "",
  "type PlaygroundConfig = {",
  "  editor: {",
  "    baseStyles: boolean;",
  "    defaultKeybindings: boolean;",
  "    history: boolean;",
  "    indentWithTab: boolean;",
  "    highlightActiveLine: boolean;",
  "    lineWrapping: boolean;",
  "  };",
  "  preview: {",
  "    includeBase: boolean;",
  "    sanitize: boolean;",
  "  };",
  "  features: {",
  "    slashCommands: boolean;",
  "    attachments: boolean;",
  "    pasteDropUploads: boolean;",
  "    selectionToolbar: boolean;",
  "    tableOfContents: boolean;",
  "  };",
  "  plugins: PluginConfig;",
  "};",
  "",
  "const defaultPluginConfig: PluginConfig = Object.fromEntries(",
  "  allPlugins.map((plugin) => [plugin.name.toLowerCase(), true])",
  ");",
  "",
  "const defaultConfig: PlaygroundConfig = {",
  "  editor: {",
  "    baseStyles: true,",
  "    defaultKeybindings: true,",
  "    history: true,",
  "    indentWithTab: true,",
  "    highlightActiveLine: true,",
  "    lineWrapping: true,",
  "  },",
  "  preview: {",
  "    includeBase: true,",
  "    sanitize: true,",
  "  },",
  "  features: {",
  "    slashCommands: true,",
  "    attachments: true,",
  "    pasteDropUploads: true,",
  "    selectionToolbar: true,",
  "    tableOfContents: true,",
  "  },",
  "  plugins: defaultPluginConfig,",
  "};",
  "```",
  "",
  "## 4. 默认文档和持久化",
  "",
  "```tsx",
  'const STORAGE_KEY = "markora-playground-contents";',
  'const STORAGE_CURRENT_KEY = "markora-playground-current";',
  'const STORAGE_VERSION_KEY = "markora-playground-version";',
  "const STORAGE_VERSION = 2;",
  "",
  "const DEFAULT_CONTENTS: Content[] = [",
  '  { id: "project-introduction", title: "项目介绍", content: projectIntroduction },',
  '  { id: "vue2-guide", title: "Ve2 接入指南", content: vue2Guide },',
  '  { id: "vue3-guide", title: "Vue3 接入指南", content: vue3Guide },',
  '  { id: "react-guide", title: "React 接入指南", content: reactGuide },',
  "];",
  "",
  "const DEFAULT_CONTENT_IDS = new Set(DEFAULT_CONTENTS.map((content) => content.id));",
  "```",
  "",
  "| 字段                  | 作用               | 建议                                         |",
  "| --------------------- | ------------------ | -------------------------------------------- |",
  "| `STORAGE_VERSION`     | 默认文档版本。     | 默认文档标题或内容变化时递增。               |",
  "| `DEFAULT_CONTENT_IDS` | 识别系统默认文档。 | 版本升级时替换默认文档，保留用户文档。       |",
  "| `content`             | Markdown 原文。    | 生产系统保存它，不保存 EditorView 内部状态。 |",
  "",
  "## 5. 主组件状态",
  "",
  "```tsx",
  "export function MarkoraReactEditor() {",
  "  const [contents, setContents] = useState<Content[]>(DEFAULT_CONTENTS);",
  "  const [currentContent, setCurrentContent] = useState(0);",
  '  const [mode, setMode] = useState<Mode>("live");',
  "  const [config, setConfig] = useState<PlaygroundConfig>(defaultConfig);",
  "  const [nodes, setNodes] = useState<MarkoraNode[]>([]);",
  "  const [output, setOutput] = useState<{ html: string; css: string } | null>(null);",
  "",
  "  const editor = useRef<ReactCodeMirrorRef>(null);",
  "  const objectUrlsRef = useRef<string[]>([]);",
  "",
  '  const theme = "light";',
  '  const cmTheme = theme === "dark" ? githubDark : githubLight;',
  '  const markoraTheme = theme === "dark" ? ThemeEnum.DARK : ThemeEnum.LIGHT;',
  "",
  "  const activePlugins = useMemo<MarkoraPlugin[]>(() => {",
  "    return allPlugins.filter((plugin) => {",
  "      const name = plugin.name.toLowerCase();",
  "      return config.plugins[name] ?? true;",
  "    });",
  "  }, [config.plugins]);",
  "}",
  "```",
  "",
  "## 6. 附件上传",
  "",
  "```tsx",
  "const uploader = useCallback(async (file: File) => {",
  "  // Demo 可以用 blob URL；生产环境必须改成真实上传接口。",
  "  const url = URL.createObjectURL(file);",
  "  objectUrlsRef.current.push(url);",
  "",
  "  return {",
  "    url,",
  "    name: file.name,",
  "    mimeType: file.type,",
  "  };",
  "}, []);",
  "",
  "useEffect(() => {",
  "  return () => {",
  "    // 释放 demo 上传产生的 blob URL。",
  "    for (const url of objectUrlsRef.current) {",
  "      URL.revokeObjectURL(url);",
  "    }",
  "    objectUrlsRef.current = [];",
  "  };",
  "}, []);",
  "```",
  "",
  "### 6.1 附件上传 API 表",
  "",
  "| 属性                      | 默认值           | 说明                                                                            |",
  "| ------------------------- | ---------------- | ------------------------------------------------------------------------------- |",
  "| `attachments.enabled`     | `false`          | 是否启用附件能力。                                                              |",
  "| `attachments.uploader`    | `undefined`      | 实际上传函数；未提供时 paste/drop 扩展不会注册，slash media 命令使用 fallback。 |",
  "| `attachments.enablePaste` | `true`           | 是否处理剪贴板文件。                                                            |",
  "| `attachments.enableDrop`  | `true`           | 是否处理拖拽文件。                                                              |",
  "| `attachments.accept`      | 类型侧默认 `*/*` | 按 `image/video/audio/file` 限制 MIME 或后缀。                                  |",
  "",
  "### 6.2 Markora 提供了什么",
  "",
  "| 阶段     | Markora 行为                                               |",
  "| -------- | ---------------------------------------------------------- |",
  "| 文件来源 | 支持 slash 文件选择、粘贴、拖拽。                          |",
  "| 上传前   | 插入 `markora-upload://task-id` 临时标记。                 |",
  "| 上传中   | 调用 `uploader(file, context)`。                           |",
  "| 上传成功 | 按附件类型替换为 Markdown 图片、音视频 HTML 或文件链接。   |",
  "| 上传失败 | 替换为 `[Upload failed: name](markora-upload://task-id)`。 |",
  "",
  "Markora 不提供对象存储、鉴权、文件扫描、断点续传、进度条或删除接口。需要这些能力时，业务侧应在 uploader 和自己的 UI 中实现。",
  "",
  "## 7. 生成 Markora extensions",
  "",
  "```tsx",
  "const extensions = useMemo<Extension[]>(",
  "  () =>",
  "    markora({",
  "      theme: markoraTheme,",
  "      baseStyles: config.editor.baseStyles,",
  "      plugins: activePlugins,",
  '      disableViewPlugin: mode === "code",',
  "      defaultKeybindings: config.editor.defaultKeybindings,",
  "      history: config.editor.history,",
  "      indentWithTab: config.editor.indentWithTab,",
  "      highlightActiveLine: config.editor.highlightActiveLine,",
  "      lineWrapping: config.editor.lineWrapping,",
  "      slashCommands: {",
  "        enabled: config.features.slashCommands,",
  "      },",
  "      selectionToolbar: {",
  "        enabled: config.features.selectionToolbar,",
  "      },",
  "      toc: {",
  '        enabled: mode === "live" && config.features.tableOfContents,',
  '        storageKey: "markora-react:toc",',
  "      },",
  "      attachments: {",
  "        enabled: config.features.attachments,",
  "        uploader: config.features.attachments ? uploader : undefined,",
  "        enablePaste: config.features.pasteDropUploads,",
  "        enableDrop: config.features.pasteDropUploads,",
  "        accept: {",
  '          image: ["image/*"],',
  '          video: ["video/*"],',
  '          audio: ["audio/*"],',
  '          file: ["*/*"],',
  "        },",
  "      },",
  "      onNodesChange: (nextNodes) => {",
  "        setNodes(nextNodes);",
  "      },",
  "    }),",
  "  [activePlugins, config.editor, config.features, markoraTheme, mode, uploader]",
  ");",
  "```",
  "",
  "不要把当前 Markdown 文本放入这个 `useMemo` 依赖。正文变化应通过 `CodeMirror value/onChange` 同步，否则每次输入都会重建扩展。",
  "",
  "## 8. 渲染编辑、预览和输出",
  "",
  "```tsx",
  "const current = contents[currentContent];",
  "",
  "return (",
  '  <main className="markora-react-shell">',
  '    {mode === "view" && output ? (',
  '      <article className="markora-preview-host">',
  "        <style>{output.css}</style>",
  "        <div dangerouslySetInnerHTML={{ __html: output.html }} />",
  "      </article>",
  '    ) : mode === "output" && output ? (',
  '      <div className="markora-output-grid">',
  "        <CodeMirror",
  "          value={output.html}",
  "          theme={cmTheme}",
  "          extensions={[html(), EditorView.lineWrapping, EditorView.editable.of(false)]}",
  "          editable={false}",
  "        />",
  "        <CodeMirror",
  "          value={output.css}",
  "          theme={cmTheme}",
  "          extensions={[css(), EditorView.lineWrapping, EditorView.editable.of(false)]}",
  "          editable={false}",
  "        />",
  "      </div>",
  "    ) : (",
  "      <CodeMirror",
  "        ref={editor}",
  "        value={current.content}",
  "        theme={cmTheme}",
  "        extensions={extensions}",
  "        basicSetup={false}",
  "        onChange={(value) => {",
  "          setContents((items) =>",
  "            items.map((item, index) => (index === currentContent ? { ...item, content: value } : item))",
  "          );",
  "        }}",
  "      />",
  "    )}",
  "  </main>",
  ");",
  "```",
  "",
  "`basicSetup={false}` 用于避免 `@uiw/react-codemirror` 默认扩展与 Markora 组装的扩展重复。",
  "",
  "## 9. 生成预览输出",
  "",
  "```tsx",
  "useEffect(() => {",
  '  if (!["view", "output"].includes(mode)) return;',
  "",
  "  let cancelled = false;",
  "",
  "  (async () => {",
  '    const markdown = contents[currentContent]?.content || "";',
  "",
  "    const htmlOutput = await preview(markdown, {",
  "      theme: markoraTheme,",
  "      plugins: activePlugins,",
  "      markdown: [],",
  "      syntaxTheme: cmTheme,",
  "      sanitize: config.preview.sanitize,",
  '      wrapperTag: "div",',
  '      wrapperClass: "markora-preview",',
  "    });",
  "",
  "    const cssOutput = generateCSS({",
  "      theme: markoraTheme,",
  "      plugins: activePlugins,",
  '      wrapperClass: "markora-preview",',
  "      includeBase: config.preview.includeBase,",
  "      syntaxTheme: cmTheme,",
  "    });",
  "",
  "    if (!cancelled) {",
  "      setOutput({ html: htmlOutput, css: cssOutput });",
  "    }",
  "  })();",
  "",
  "  return () => {",
  "    cancelled = true;",
  "  };",
  "}, [activePlugins, cmTheme, config.preview, contents, currentContent, markoraTheme, mode]);",
  "```",
  "",
  "| API                       | 默认值              | React 建议                        |",
  "| ------------------------- | ------------------- | --------------------------------- |",
  "| `preview.plugins`         | `[]`                | 使用 `activePlugins`。            |",
  "| `preview.sanitize`        | `true`              | 用户内容保持开启。                |",
  '| `preview.wrapperClass`    | `"markora-preview"` | 和 CSS 生成保持一致。             |',
  "| `generateCSS.includeBase` | `true`              | 需要完全自定义 spacing 时再关闭。 |",
  "| `generateCSS.syntaxTheme` | `undefined`         | 使用当前 CodeMirror theme。       |",
  "",
  "## 10. Markora 配置速查",
  "",
  "| 配置                       | 默认值           | React 建议                                |",
  "| -------------------------- | ---------------- | ----------------------------------------- |",
  "| `theme`                    | `ThemeEnum.AUTO` | 从主题状态映射为 `ThemeEnum.LIGHT/DARK`。 |",
  "| `baseStyles`               | `true`           | 初次接入保持开启。                        |",
  "| `plugins`                  | `[]`             | 传 `activePlugins`。                      |",
  '| `disableViewPlugin`        | `false`          | `mode === "code"` 时设为 `true`。         |',
  "| `defaultKeybindings`       | `true`           | 保持开启。                                |",
  "| `history`                  | `true`           | 保持开启。                                |",
  "| `indentWithTab`            | `true`           | 保持开启。                                |",
  "| `highlightActiveLine`      | `true`           | 源码模式有效。                            |",
  "| `lineWrapping`             | `true`           | 保持开启。                                |",
  "| `slashCommands.enabled`    | `true`           | feature toggle 控制。                     |",
  "| `selectionToolbar.enabled` | `true`           | feature toggle 控制。                     |",
  "| `toc.enabled`              | `true`           | live 模式开启。                           |",
  "| `attachments.enabled`      | `false`          | 有 uploader 后开启。                      |",
  "",
  "## 11. 插件体系",
  "",
  "React 接入不改变插件模型。自定义插件继承 `MarkoraPlugin`：",
  "",
  "```tsx",
  'import type { DecorationContext } from "@refinex/markora/editor";',
  'import { MarkoraPlugin } from "@refinex/markora/editor";',
  "",
  "class MentionPlugin extends MarkoraPlugin {",
  '  readonly name = "mention";',
  '  readonly version = "1.0.0";',
  "",
  "  buildDecorations(ctx: DecorationContext): void {",
  "    // 在这里扫描 ctx.view.state.doc。",
  "    // 需要装饰时向 ctx.decorations 追加 Decoration.range(...)。",
  "  }",
  "}",
  "```",
  "",
  "| 插件方法              | 用途                     |",
  "| --------------------- | ------------------------ |",
  "| `getExtensions()`     | 添加 CodeMirror 扩展。   |",
  "| `getMarkdownConfig()` | 添加 Markdown 解析扩展。 |",
  "| `getKeymap()`         | 添加快捷键。             |",
  "| `buildDecorations()`  | 编辑态 decoration。      |",
  "| `renderToHTML()`      | preview HTML。           |",
  "| `getPreviewStyles()`  | preview CSS。            |",
  "",
  "## 12. 生产验收清单",
  "",
  "- `extensions` 不随每次输入重建。",
  "- `basicSetup={false}`，避免扩展重复。",
  "- 编辑、源码、预览、输出模式都能切换。",
  "- 附件上传成功、失败、超限和权限错误都有用户可见反馈。",
  "- slash media 命令和 paste/drop 复用同一个 uploader。",
  "- `preview()` 与 `generateCSS()` 使用同一组插件、主题和 syntax theme。",
  "- `blob:` URL 在组件卸载时释放。",
  "- 用户 Markdown 原文已保存到业务存储。",
].join("\n");
