// playground/react-playground/app/data/md/vue2-guide.en.ts
export default [
  "# Vue 2 Integration Guide",
  "",
  "This guide targets Vue 2 projects, with the goal of integrating a Mardora editor that matches the Vue 2 playground in quality: rich Markdown editing, source mode, preview mode, HTML/CSS output, plugin toggles, slash commands, attachment uploads, outline, theme switching, and local persistence.",
  "",
  "## 1. Install dependencies",
  "",
  "```shell",
  "npm install mardora",
  "```",
  "",
  "If you also want to display the HTML/CSS output view, install `@codemirror/lang-html`, `@codemirror/lang-css`, and `@uiw/codemirror-theme-github` only for that optional output panel.",
  "",
  "Vue 2 projects typically also need TypeScript, the Vue 2 loader, and the bundler's own configuration. Mardora requires no Vue-2-specific adapter; you use the CodeMirror `EditorView` directly.",
  "",
  "## 2. Prepare the container",
  "",
  "```vue",
  "<template>",
  '  <section class="mardora-shell">',
  '    <div class="toolbar">',
  "      <button @click=\"mode = 'live'\">Edit</button>",
  "      <button @click=\"mode = 'code'\">Source</button>",
  "      <button @click=\"mode = 'view'\">Preview</button>",
  "      <button @click=\"mode = 'output'\">Output</button>",
  "    </div>",
  "",
  '    <div v-if="mode === \'view\'" ref="previewHost" class="preview-host">',
  '      <div v-html="previewOutput.html" />',
  "    </div>",
  "",
  '    <div v-else-if="mode === \'output\'" class="output-grid">',
  '      <div ref="htmlOutputHost" />',
  '      <div ref="cssOutputHost" />',
  "    </div>",
  "",
  '    <div v-else ref="editorHost" class="editor-host" />',
  "  </section>",
  "</template>",
  "```",
  "",
  "It is recommended to give the editor host an explicit height, otherwise CodeMirror's scroll region is hard to stabilize:",
  "",
  "```css",
  ".mardora-shell {",
  "  height: 100vh;",
  "  display: flex;",
  "  flex-direction: column;",
  "}",
  "",
  ".editor-host,",
  ".preview-host,",
  ".output-grid {",
  "  flex: 1;",
  "  min-height: 0;",
  "  overflow: auto;",
  "}",
  "",
  ".output-grid {",
  "  display: grid;",
  "  grid-template-columns: 1fr 1fr;",
  "}",
  "```",
  "",
  "## 3. Define the config state",
  "",
  "The Vue 2 playground's config can be split into four blocks: editor, preview, features, and plugins:",
  "",
  "```ts",
  'import { allPlugins } from "mardora/plugins";',
  "",
  "export type PluginConfig = Record<string, boolean>;",
  "",
  "export type PlaygroundConfig = {",
  '  locale: "zh-CN" | "en-US";',
  "  editor: {",
  "    baseStyles: boolean;",
  "    defaultKeybindings: boolean;",
  "    history: boolean;",
  "    indentWithTab: boolean;",
  "    highlightActiveLine: boolean;",
  "    lineWrapping: boolean;",
  "  };",
  "  preview: {",
  "    includeBase: boolean;",
  "    sanitize: boolean;",
  '    contentWidth: "regular" | "wide";',
  "  };",
  "  features: {",
  "    slashCommands: boolean;",
  "    attachments: boolean;",
  "    pasteDropUploads: boolean;",
  "    selectionToolbar: boolean;",
  "    tableOfContents: boolean;",
  "  };",
  "  plugins: PluginConfig;",
  "};",
  "",
  "export function createDefaultPluginConfig(): PluginConfig {",
  "  return Object.fromEntries(allPlugins.map((plugin) => [plugin.name.toLowerCase(), true]));",
  "}",
  "",
  "export function getActivePlugins(pluginConfig: PluginConfig) {",
  "  return allPlugins.filter((plugin) => pluginConfig[plugin.name.toLowerCase()] !== false);",
  "}",
  "```",
  "",
  "Default config:",
  "",
  "```ts",
  "export const defaultConfig: PlaygroundConfig = {",
  '  locale: "zh-CN",',
  "  editor: {",
  "    baseStyles: true,",
  "    defaultKeybindings: true,",
  "    history: true,",
  "    indentWithTab: true,",
  "    highlightActiveLine: true,",
  "    lineWrapping: true,",
  "  },",
  "  preview: {",
  "    includeBase: true,",
  "    sanitize: true,",
  '    contentWidth: "regular",',
  "  },",
  "  features: {",
  "    slashCommands: true,",
  "    attachments: true,",
  "    pasteDropUploads: true,",
  "    selectionToolbar: true,",
  "    tableOfContents: true,",
  "  },",
  "  plugins: createDefaultPluginConfig(),",
  "};",
  "```",
  "",
  "## 4. Create the editor",
  "",
  "```ts",
  'import Vue from "vue";',
  'import { html } from "@codemirror/lang-html";',
  'import { css } from "@codemirror/lang-css";',
  'import { githubDark, githubLight } from "@uiw/codemirror-theme-github";',
  'import type { MardoraNode, MardoraTocItem } from "mardora/editor";',
  'import { EditorState, EditorView, mardora, ThemeEnum } from "mardora/editor";',
  'import { extractPreviewTocFromMarkdown, generateCSS, preview } from "mardora/preview";',
  'import { getActivePlugins } from "./playground-config";',
  "",
  "export default Vue.extend({",
  "  data() {",
  "    return {",
  '      mode: "live" as "live" | "code" | "view" | "output",',
  '      theme: "light" as "light" | "dark",',
  '      content: "# Hello, Mardora",',
  "      editorView: null as EditorView | null,",
  "      htmlView: null as EditorView | null,",
  "      cssView: null as EditorView | null,",
  "      previewStyleElement: null as HTMLStyleElement | null,",
  '      previewOutput: { html: "", css: "" },',
  "      previewToc: [] as MardoraTocItem[],",
  "      objectUrls: [] as string[],",
  "      internalUpdate: false,",
  "      config: defaultConfig,",
  "    };",
  "  },",
  "",
  "  mounted() {",
  "    this.rebuildForMode();",
  "  },",
  "",
  "  beforeDestroy() {",
  "    this.destroyViews();",
  "    this.revokeObjectUrls();",
  "  },",
  "",
  "  watch: {",
  "    mode() {",
  "      this.rebuildForMode();",
  "    },",
  "    theme() {",
  "      this.rebuildForMode();",
  "    },",
  "    config: {",
  "      deep: true,",
  "      handler() {",
  "        this.rebuildForMode();",
  "      },",
  "    },",
  "    content(next: string) {",
  "      if (!this.editorView) return;",
  "      if (next === this.editorView.state.doc.toString()) return;",
  "",
  "      this.internalUpdate = true;",
  "      this.editorView.dispatch({",
  "        changes: {",
  "          from: 0,",
  "          to: this.editorView.state.doc.length,",
  "          insert: next,",
  "        },",
  "      });",
  "      this.internalUpdate = false;",
  "    },",
  "  },",
  "",
  "  methods: {",
  "    cmTheme() {",
  '      return this.theme === "dark" ? githubDark : githubLight;',
  "    },",
  "",
  "    mardoraTheme() {",
  '      return this.theme === "dark" ? ThemeEnum.DARK : ThemeEnum.LIGHT;',
  "    },",
  "",
  "    async mockUploader(file: File) {",
  "      const url = URL.createObjectURL(file);",
  "      this.objectUrls.push(url);",
  "      return {",
  "        url,",
  "        name: file.name,",
  "        mimeType: file.type,",
  "      };",
  "    },",
  "",
  "    rebuildForMode() {",
  "      this.$nextTick(() => {",
  "        this.destroyViews();",
  "",
  '        if (this.mode === "view" || this.mode === "output") {',
  "          this.renderPreview();",
  "          return;",
  "        }",
  "",
  "        this.createEditorView();",
  "      });",
  "    },",
  "",
  "    createEditorView() {",
  "      const parent = this.$refs.editorHost as HTMLElement | undefined;",
  "      if (!parent) return;",
  "",
  "      const updateListener = EditorView.updateListener.of((update) => {",
  "        if (!update.docChanged || this.internalUpdate) return;",
  "        this.content = update.state.doc.toString();",
  "      });",
  "",
  "      this.editorView = new EditorView({",
  "        parent,",
  "        state: EditorState.create({",
  "          doc: this.content,",
  "          extensions: [",
  "            this.cmTheme(),",
  "            mardora({",
  "              theme: this.mardoraTheme(),",
  "              locale: this.config.locale,",
  "              baseStyles: this.config.editor.baseStyles,",
  "              contentWidth: this.config.preview.contentWidth === \"wide\" ? \"full\" : \"default\",",
  "              plugins: getActivePlugins(this.config.plugins),",
  "              markdown: [],",
  "              extensions: [],",
  "              keymap: [],",
  '              disableViewPlugin: this.mode === "code",',
  "              defaultKeybindings: this.config.editor.defaultKeybindings,",
  "              history: this.config.editor.history,",
  "              indentWithTab: this.config.editor.indentWithTab,",
  "              highlightActiveLine: this.config.editor.highlightActiveLine,",
  "              lineWrapping: this.config.editor.lineWrapping,",
  "              slashCommands: {",
  "                enabled: this.config.features.slashCommands,",
  "              },",
  "              selectionToolbar: {",
  "                enabled: this.config.features.selectionToolbar,",
  "              },",
  "              toc: {",
  '                enabled: this.mode === "live" && this.config.features.tableOfContents,',
  "                onTocChange: (items: MardoraTocItem[]) => {",
  "                  this.previewToc = items;",
  "                },",
  "              },",
  "              attachments: {",
  "                enabled: this.config.features.attachments,",
  "                uploader: this.config.features.attachments ? this.mockUploader : undefined,",
  "                enablePaste: this.config.features.pasteDropUploads,",
  "                enableDrop: this.config.features.pasteDropUploads,",
  "                accept: {",
  '                  image: ["image/*"],',
  '                  video: ["video/*"],',
  '                  audio: ["audio/*"],',
  '                  file: ["*/*"],',
  "                },",
  "              },",
  "              onNodesChange: (nodes: MardoraNode[]) => {",
  '                this.$emit("nodes-change", nodes);',
  "              },",
  "            }),",
  "            updateListener,",
  "          ],",
  "        }),",
  "      });",
  "    },",
  "  },",
  "});",
  "```",
  "",
  "A production uploader must not return `blob:` URLs. It should upload to a back end, object store, or CDN and return a long-lived `url`.",
  "",
  "## 5. Implement preview and output modes",
  "",
  "```ts",
  "async function renderPreview(this: Vue & any) {",
  "  const plugins = getActivePlugins(this.config.plugins);",
  "  const syntaxTheme = this.cmTheme();",
  "",
  "  const htmlOutput = await preview(this.content, {",
  "    theme: this.mardoraTheme(),",
  "    plugins,",
  "    markdown: [],",
  "    syntaxTheme,",
  "    sanitize: this.config.preview.sanitize,",
  '    wrapperTag: "div",',
  '    wrapperClass: "mardora-preview vue2-preview",',
  "  });",
  "",
  "  const cssOutput = generateCSS({",
  "    theme: this.mardoraTheme(),",
  "    plugins,",
  '    wrapperClass: "mardora-preview",',
  "    includeBase: this.config.preview.includeBase,",
  "    syntaxTheme,",
  "  });",
  "",
  "  this.previewOutput = { html: htmlOutput, css: cssOutput };",
  "  this.previewToc = extractPreviewTocFromMarkdown(this.content);",
  "",
  "  this.$nextTick(() => {",
  '    if (this.mode === "view") {',
  "      this.updatePreviewStyles();",
  "    }",
  '    if (this.mode === "output") {',
  "      this.createOutputViews();",
  "    }",
  "  });",
  "}",
  "",
  "function updatePreviewStyles(this: Vue & any) {",
  "  const previewHost = this.$refs.previewHost as HTMLElement | undefined;",
  "  if (!previewHost) return;",
  "",
  "  if (!this.previewStyleElement) {",
  '    this.previewStyleElement = document.createElement("style");',
  "    previewHost.prepend(this.previewStyleElement);",
  "  }",
  "",
  "  this.previewStyleElement.textContent = this.previewOutput.css;",
  "}",
  "",
  "function createOutputViews(this: Vue & any) {",
  "  const htmlParent = this.$refs.htmlOutputHost as HTMLElement | undefined;",
  "  const cssParent = this.$refs.cssOutputHost as HTMLElement | undefined;",
  "  if (!htmlParent || !cssParent) return;",
  "",
  "  this.htmlView = new EditorView({",
  "    parent: htmlParent,",
  "    state: EditorState.create({",
  "      doc: this.previewOutput.html,",
  "      extensions: [this.cmTheme(), html(), EditorView.lineWrapping, EditorState.readOnly.of(true)],",
  "    }),",
  "  });",
  "",
  "  this.cssView = new EditorView({",
  "    parent: cssParent,",
  "    state: EditorState.create({",
  "      doc: this.previewOutput.css,",
  "      extensions: [this.cmTheme(), css(), EditorView.lineWrapping, EditorState.readOnly.of(true)],",
  "    }),",
  "  });",
  "}",
  "```",
  "",
  "## 6. Outline integration",
  "",
  "In live edit mode you can use `toc.onTocChange` to get the edit-state outline. In preview mode prefer `extractPreviewTocFromMarkdown(markdown)` so you don't depend on an editor instance that has been destroyed.",
  "",
  "```vue",
  '<aside v-if="config.features.tableOfContents" class="preview-toc">',
  "  <button",
  '    v-for="item in previewToc"',
  '    :key="item.id"',
  '    :data-level="item.level"',
  '    :class="{ active: item.active }"',
  '    @click="jumpToc(item)"',
  "  >",
  "    {{ item.text }}",
  "  </button>",
  "</aside>",
  "```",
  "",
  "```ts",
  "function jumpToc(this: Vue & any, item: MardoraTocItem) {",
  '  if (this.mode === "view") {',
  "    const host = this.$refs.previewHost as HTMLElement | undefined;",
  "    const target = host?.querySelector(`#${CSS.escape(item.id)}`) as HTMLElement | null;",
  '    target?.scrollIntoView({ block: "start" });',
  "    return;",
  "  }",
  "",
  '  if (this.editorView && typeof item.from === "number") {',
  "    this.editorView.dispatch({",
  "      selection: { anchor: item.from },",
  '      effects: EditorView.scrollIntoView(item.from, { y: "start" }),',
  "    });",
  "    this.editorView.focus();",
  "  }",
  "}",
  "```",
  "",
  "## 7. Local persistence",
  "",
  "The playground refreshes default documents by version number while keeping user-created documents:",
  "",
  "```ts",
  'export const STORAGE_CONTENTS_KEY = "mardora-vue2-playground-contents";',
  'export const STORAGE_CURRENT_KEY = "mardora-vue2-playground-current";',
  'export const STORAGE_VERSION_KEY = "mardora-vue2-playground-version";',
  "export const STORAGE_VERSION = 2;",
  "",
  "export function loadSnapshot(defaultContents: Content[]) {",
  "  const storedContents = localStorage.getItem(STORAGE_CONTENTS_KEY);",
  "  const storedVersion = localStorage.getItem(STORAGE_VERSION_KEY);",
  "  const versionMatches = storedVersion === String(STORAGE_VERSION);",
  "",
  "  if (storedContents && versionMatches) {",
  "    return JSON.parse(storedContents) as Content[];",
  "  }",
  "",
  "  localStorage.setItem(STORAGE_CONTENTS_KEY, JSON.stringify(defaultContents));",
  "  localStorage.setItem(STORAGE_VERSION_KEY, String(STORAGE_VERSION));",
  "  return defaultContents;",
  "}",
  "```",
  "",
  "Raise `STORAGE_VERSION` whenever you change the default document content or titles, otherwise existing users' local cache will not refresh automatically.",
  "",
  "## 8. Lifecycle cleanup",
  "",
  "```ts",
  "function destroyViews(this: Vue & any) {",
  "  this.editorView?.destroy();",
  "  this.htmlView?.destroy();",
  "  this.cssView?.destroy();",
  "  this.editorView = null;",
  "  this.htmlView = null;",
  "  this.cssView = null;",
  "",
  "  if (this.previewStyleElement) {",
  "    this.previewStyleElement.remove();",
  "    this.previewStyleElement = null;",
  "  }",
  "}",
  "",
  "function revokeObjectUrls(this: Vue & any) {",
  "  for (const url of this.objectUrls) {",
  "    URL.revokeObjectURL(url);",
  "  }",
  "  this.objectUrls = [];",
  "}",
  "```",
  "",
  "The most common mistake in Vue 2 is forgetting to destroy the old `EditorView` after a watcher triggers a rebuild, and forgetting to release the `blob:` URLs produced by the attachment-upload demo.",
  "",
  "## 9. Plugins and API standards",
  "",
  "Vue 2 integration does not require working around Mardora's standard API. Use directly:",
  "",
  "- `mardora/editor`: editor extensions, `ThemeEnum`, `MardoraNode`, `MardoraTocItem`.",
  "- `mardora/plugins`: `allPlugins`, `essentialPlugins`, and individual plugin classes.",
  "- `mardora/preview`: `preview()`, `generateCSS()`, `extractPreviewTocFromMarkdown()`.",
  "- CodeMirror 6: `EditorState`, `EditorView`, `Extension`, `updateListener`, `EditorView.lineWrapping`.",
  "- Browser API: `File`, `FormData`, `URL.createObjectURL`, paste, drop.",
  "",
  "If you want custom syntax, create a `MardoraPlugin` and provide `getMarkdownConfig()`; for custom edit-state visuals, provide `buildDecorations()`; to keep preview in sync, provide `renderToHTML()` and `getPreviewStyles()`.",
  "",
  "## 10. Acceptance checklist",
  "",
  "- Edit, source, preview, and output modes all switch correctly.",
  "- After typing, the Vue 2 state and the CodeMirror document stay consistent.",
  "- With all `allPlugins` enabled, headings, lists, tables, images, code blocks, math, Mermaid, HTML, and Emoji all render.",
  "- Slash commands, the selection toolbar, and attachment uploads all react to their config toggles.",
  "- Preview HTML and CSS are consistent with the current plugins, theme, and syntax theme.",
  "- The outline jumps correctly in both edit and preview states.",
  "- When the component is destroyed, the `EditorView` and `blob:` URLs have been cleaned up.",
  "- After default-document changes, the storage version is bumped and stale caches refresh defaults while keeping user documents.",
].join("\n");

// playground/react-playground/app/data/md/react-guide.en.ts
export default [
  "# React Integration Guide",
  "",
  "This guide targets React projects, with the goal of integrating a Mardora editor that matches the React playground in quality: rich Markdown editing, source mode, preview mode, HTML/CSS output, plugin toggles, slash commands, attachment uploads, theme switching, local persistence, and node debugging.",
  "",
  "The React playground wraps CodeMirror with `@uiw/react-codemirror`. You can also create an `EditorView` manually, but if your app already uses React, `@uiw/react-codemirror` removes boilerplate around lifecycle management.",
  "",
  "## 1. Install dependencies",
  "",
  "```shell",
  "npm install mardora",
  "npm install @uiw/react-codemirror",
  "```",
  "",
  "Optional HTML/CSS output panels like the playground also use `@codemirror/lang-html`, `@codemirror/lang-css`, and `@uiw/codemirror-theme-github`; install them only if you keep that panel.",
  "",
  "If you use the Next.js App Router, the editor component must be a client component:",
  "",
  "```tsx",
  '"use client";',
  "```",
  "",
  "## 2. Define content and config",
  "",
  "```tsx",
  'import { useCallback, useEffect, useMemo, useRef, useState } from "react";',
  'import CodeMirror, { ReactCodeMirrorRef } from "@uiw/react-codemirror";',
  'import { githubDark, githubLight } from "@uiw/codemirror-theme-github";',
  'import { html } from "@codemirror/lang-html";',
  'import { css } from "@codemirror/lang-css";',
  'import { EditorView, Extension, mardora, MardoraNode, MardoraPlugin, ThemeEnum } from "mardora/editor";',
  'import { allPlugins } from "mardora/plugins";',
  'import { generateCSS, preview } from "mardora/preview";',
  "",
  "type Content = {",
  "  id: string;",
  "  title: string;",
  "  content: string;",
  "};",
  "",
  'type PlaygroundMode = "live" | "view" | "code" | "output";',
  "type PluginConfig = Record<string, boolean>;",
  "",
  "type PlaygroundConfig = {",
  "  editor: {",
  "    baseStyles: boolean;",
  "    defaultKeybindings: boolean;",
  "    history: boolean;",
  "    indentWithTab: boolean;",
  "    highlightActiveLine: boolean;",
  "    lineWrapping: boolean;",
  "  };",
  "  preview: {",
  "    includeBase: boolean;",
  "    sanitize: boolean;",
  "    contentWidth: \"regular\" | \"wide\";",
  "  };",
  "  features: {",
  "    slashCommands: boolean;",
  "    attachments: boolean;",
  "    pasteDropUploads: boolean;",
  "    selectionToolbar: boolean;",
  "    tableOfContents: boolean;",
  "  };",
  "  plugins: PluginConfig;",
  "};",
  "",
  "const defaultPluginConfig: PluginConfig = Object.fromEntries(",
  "  allPlugins.map((plugin) => [plugin.name.toLowerCase(), true])",
  ");",
  "",
  "const defaultConfig: PlaygroundConfig = {",
  "  editor: {",
  "    baseStyles: true,",
  "    defaultKeybindings: true,",
  "    history: true,",
  "    indentWithTab: true,",
  "    highlightActiveLine: true,",
  "    lineWrapping: true,",
  "  },",
  "  preview: {",
  "    includeBase: true,",
  "    sanitize: true,",
  "    contentWidth: \"regular\",",
  "  },",
  "  features: {",
  "    slashCommands: true,",
  "    attachments: true,",
  "    pasteDropUploads: true,",
  "    selectionToolbar: true,",
  "    tableOfContents: true,",
  "  },",
  "  plugins: defaultPluginConfig,",
  "};",
  "```",
  "",
  "## 3. Organize the default documents",
  "",
  "The React playground uses fixed ids and a version number to refresh the default documents:",
  "",
  "```tsx",
  'const STORAGE_KEY = "mardora-playground-contents";',
  'const STORAGE_CURRENT_KEY = "mardora-playground-current";',
  'const STORAGE_VERSION_KEY = "mardora-playground-version";',
  "const STORAGE_VERSION = 2;",
  "",
  "const DEFAULT_CONTENTS: Content[] = [",
  '  { id: "project-introduction", title: "Project Introduction", content: projectIntroduction },',
  '  { id: "vue2-guide", title: "Vue 2 Integration Guide", content: vue2Guide },',
  '  { id: "vue3-guide", title: "Vue 3 Integration Guide", content: vue3Guide },',
  '  { id: "react-guide", title: "React Integration Guide", content: reactGuide },',
  "];",
  "",
  "const DEFAULT_CONTENT_IDS = new Set(DEFAULT_CONTENTS.map((content) => content.id));",
  "```",
  "",
  "Raise `STORAGE_VERSION` whenever the default documents change. On a version mismatch, replace the fixed-id defaults with the new versions and keep user-created documents.",
  "",
  "## 4. Prepare the uploader and plugin state",
  "",
  "```tsx",
  "export function MardoraReactEditor() {",
  "  const [contents, setContents] = useState<Content[]>(DEFAULT_CONTENTS);",
  "  const [currentContent, setCurrentContent] = useState(0);",
  '  const [mode, setMode] = useState<PlaygroundMode>("live");',
  "  const [config, setConfig] = useState<PlaygroundConfig>(defaultConfig);",
  "  const [nodes, setNodes] = useState<MardoraNode[]>([]);",
  "  const [output, setOutput] = useState<{ html: string; css: string } | null>(null);",
  "  const editor = useRef<ReactCodeMirrorRef>(null);",
  "  const objectUrlsRef = useRef<string[]>([]);",
  "",
  '  const theme = "light";',
  '  const cmTheme = theme === "dark" ? githubDark : githubLight;',
  '  const mardoraTheme = theme === "dark" ? ThemeEnum.DARK : ThemeEnum.LIGHT;',
  "",
  "  const mockUploader = useCallback(async (file: File) => {",
  "    const url = URL.createObjectURL(file);",
  "    objectUrlsRef.current.push(url);",
  "    return {",
  "      url,",
  "      name: file.name,",
  "      mimeType: file.type,",
  "    };",
  "  }, []);",
  "",
  "  const activePlugins = useMemo<MardoraPlugin[]>(() => {",
  "    return allPlugins.filter((plugin) => {",
  "      const name = plugin.name.toLowerCase();",
  "      return config.plugins[name] ?? true;",
  "    });",
  "  }, [config.plugins]);",
  "",
  "  useEffect(() => {",
  "    return () => {",
  "      for (const url of objectUrlsRef.current) {",
  "        URL.revokeObjectURL(url);",
  "      }",
  "      objectUrlsRef.current = [];",
  "    };",
  "  }, []);",
  "}",
  "```",
  "",
  "A production uploader should upload to a back end, object store, or CDN and return a long-lived URL. `blob:` URLs are only suitable for playgrounds or local demos.",
  "",
  "## 5. Create the Mardora extensions",
  "",
  "```tsx",
  "const extensions = useMemo<Extension[]>(",
  "  () =>",
  "    mardora({",
  "      theme: mardoraTheme,",
  "      baseStyles: config.editor.baseStyles,",
  "      contentWidth: config.preview.contentWidth === \"wide\" ? \"full\" : \"default\",",
  "      plugins: activePlugins,",
  "      markdown: [],",
  "      extensions: [],",
  "      keymap: [],",
  '      disableViewPlugin: mode === "code",',
  "      defaultKeybindings: config.editor.defaultKeybindings,",
  "      history: config.editor.history,",
  "      indentWithTab: config.editor.indentWithTab,",
  "      highlightActiveLine: config.editor.highlightActiveLine,",
  "      lineWrapping: config.editor.lineWrapping,",
  "      slashCommands: {",
  "        enabled: config.features.slashCommands,",
  "      },",
  "      selectionToolbar: {",
  "        enabled: config.features.selectionToolbar,",
  "      },",
  "      toc: {",
  '        enabled: mode === "live" && config.features.tableOfContents,',
  "      },",
  "      attachments: {",
  "        enabled: config.features.attachments,",
  "        uploader: config.features.attachments ? mockUploader : undefined,",
  "        enablePaste: config.features.pasteDropUploads,",
  "        enableDrop: config.features.pasteDropUploads,",
  "        accept: {",
  '          image: ["image/*"],',
  '          video: ["video/*"],',
  '          audio: ["audio/*"],',
  '          file: ["*/*"],',
  "        },",
  "      },",
  "      onNodesChange: (nextNodes) => {",
  "        setNodes(nextNodes);",
  "      },",
  "    }),",
  "  [activePlugins, config.editor, config.features, mardoraTheme, mockUploader, mode]",
  ");",
  "```",
  "",
  "The key concern in React is making sure `extensions` only recomputes when the options it actually depends on change. Never put the Markdown text being typed into the `useMemo` deps, or you will trigger needless extension rebuilds.",
  "",
  "## 6. Render the editor",
  "",
  "```tsx",
  "const current = contents[currentContent];",
  "",
  "return (",
  '  <main className="mardora-shell">',
  '    {mode === "view" && output ? (',
  '      <div className="preview-host">',
  "        <style>{output.css}</style>",
  "        <div dangerouslySetInnerHTML={{ __html: output.html }} />",
  "      </div>",
  '    ) : mode === "output" && output ? (',
  '      <div className="output-grid">',
  "        <CodeMirror",
  "          value={output.html}",
  "          theme={cmTheme}",
  "          extensions={[html(), EditorView.lineWrapping, EditorView.editable.of(false)]}",
  "          editable={false}",
  "        />",
  "        <CodeMirror",
  "          value={output.css}",
  "          theme={cmTheme}",
  "          extensions={[css(), EditorView.lineWrapping, EditorView.editable.of(false)]}",
  "          editable={false}",
  "        />",
  "      </div>",
  "    ) : (",
  "      <CodeMirror",
  "        ref={editor}",
  "        value={current.content}",
  "        theme={cmTheme}",
  "        extensions={extensions}",
  "        basicSetup={false}",
  "        onChange={(value) => {",
  "          setContents((items) =>",
  "            items.map((item, index) => (index === currentContent ? { ...item, content: value } : item))",
  "          );",
  "        }}",
  "      />",
  "    )}",
  "  </main>",
  ");",
  "```",
  "",
  "`basicSetup={false}` prevents `@uiw/react-codemirror`'s default capabilities from duplicating the CodeMirror capabilities Mardora assembles itself. When you need extra extensions, add them via `mardora({ extensions: [...] })` or via the outer `extensions={[...extensions, extra]}`.",
  "",
  "## 7. Generate the preview output",
  "",
  "```tsx",
  "useEffect(() => {",
  '  if (!["view", "output"].includes(mode)) return;',
  "",
  "  let cancelled = false;",
  "",
  "  (async () => {",
  '    const markdown = contents[currentContent]?.content || "";',
  "",
  "    const htmlOutput = await preview(markdown, {",
  "      theme: mardoraTheme,",
  "      plugins: activePlugins,",
  "      markdown: [],",
  "      syntaxTheme: cmTheme,",
  "      sanitize: config.preview.sanitize,",
  '      wrapperTag: "div",',
  '      wrapperClass: "mardora-preview",',
  "    });",
  "",
  "    const cssOutput = generateCSS({",
  "      theme: mardoraTheme,",
  "      plugins: activePlugins,",
  '      wrapperClass: "mardora-preview",',
  "      includeBase: config.preview.includeBase,",
  "      syntaxTheme: cmTheme,",
  "    });",
  "",
  "    if (!cancelled) {",
  "      setOutput({ html: htmlOutput, css: cssOutput });",
  "    }",
  "  })();",
  "",
  "  return () => {",
  "    cancelled = true;",
  "  };",
  "}, [activePlugins, cmTheme, config.preview, contents, currentContent, mardoraTheme, mode]);",
  "```",
  "",
  "`preview()` and `generateCSS()` must use the same set of plugins, theme, and syntax theme. Otherwise the edit state, preview state, and output state will diverge visually or in HTML behavior.",
  "",
  "## 8. Local persistence",
  "",
  "```tsx",
  "useEffect(() => {",
  "  const storedContents = localStorage.getItem(STORAGE_KEY);",
  "  const storedCurrent = localStorage.getItem(STORAGE_CURRENT_KEY);",
  "  const storedVersion = localStorage.getItem(STORAGE_VERSION_KEY);",
  "  const isOutdated = storedVersion !== String(STORAGE_VERSION);",
  "",
  "  if (storedContents && !isOutdated) {",
  "    setContents(JSON.parse(storedContents) as Content[]);",
  '    setCurrentContent(Number.parseInt(storedCurrent || "0", 10));',
  "    return;",
  "  }",
  "",
  "  if (storedContents && isOutdated) {",
  "    const parsed = JSON.parse(storedContents) as Content[];",
  "    const userContents = parsed.filter((content) => !DEFAULT_CONTENT_IDS.has(content.id));",
  "    const merged = [...DEFAULT_CONTENTS, ...userContents];",
  "    setContents(merged);",
  "    setCurrentContent(0);",
  "    localStorage.setItem(STORAGE_KEY, JSON.stringify(merged));",
  '    localStorage.setItem(STORAGE_CURRENT_KEY, "0");',
  "    localStorage.setItem(STORAGE_VERSION_KEY, String(STORAGE_VERSION));",
  "    return;",
  "  }",
  "",
  "  localStorage.setItem(STORAGE_KEY, JSON.stringify(DEFAULT_CONTENTS));",
  '  localStorage.setItem(STORAGE_CURRENT_KEY, "0");',
  "  localStorage.setItem(STORAGE_VERSION_KEY, String(STORAGE_VERSION));",
  "}, []);",
  "```",
  "",
  "Debounce saves so you don't write to localStorage on every keystroke.",
  "",
  "## 9. Plugin system",
  "",
  "React integration uses the same `MardoraPlugin`:",
  "",
  "```tsx",
  'import type { DecorationContext } from "mardora/editor";',
  'import { MardoraPlugin } from "mardora/editor";',
  "",
  "class MentionPlugin extends MardoraPlugin {",
  '  readonly name = "mention";',
  '  readonly version = "1.0.0";',
  "",
  "  buildDecorations(ctx: DecorationContext): void {",
  "    // Read ctx.view.state.doc and append Decorations to ctx.decorations.",
  "  }",
  "}",
  "```",
  "",
  "Plugins can override at the same time:",
  "",
  "- `getExtensions()`: add CodeMirror extensions.",
  "- `getMarkdownConfig()`: extend Lezer Markdown grammar.",
  "- `getKeymap()`: add keyboard shortcuts.",
  "- `buildDecorations()`: contribute edit-state decorations.",
  "- `renderToHTML()`: contribute preview HTML.",
  "- `getPreviewStyles()`: contribute preview CSS.",
  "",
  "In your app you can merge custom plugins with the built-in ones:",
  "",
  "```tsx",
  "const plugins = useMemo(() => [...activePlugins, new MentionPlugin()], [activePlugins]);",
  "```",
  "",
  "## 10. Supported API standards",
  "",
  "For React integration, use directly:",
  "",
  "- `mardora/editor`: `mardora()`, `ThemeEnum`, `MardoraPlugin`, `MardoraNode`, TOC/attachment/selection-toolbar types.",
  "- `mardora/plugins`: `allPlugins`, `essentialPlugins`, and individual plugin classes.",
  "- `mardora/preview`: `preview()`, `generateCSS()`, `extractPreviewTocFromMarkdown()`.",
  "- CodeMirror 6: `Extension`, `EditorView`, `EditorState`, `KeyBinding`, `updateListener`.",
  "- Lezer Markdown: plugin-level `MarkdownConfig`.",
  "- React: `useMemo` for extensions, `useEffect` for preview and persistence, `useRef` for editor refs and resource cleanup.",
  "- Browser API: `File`, `FormData`, paste, drop, `URL.createObjectURL`.",
  "",
  "## 11. Acceptance checklist",
  "",
  "- Edit, source, preview, and output modes all switch correctly.",
  "- React state and the CodeMirror value stay in sync two-way, without input lag or rebuild jitter.",
  "- With all `allPlugins` enabled, headings, lists, tables, images, code blocks, math, Mermaid, HTML, and Emoji all render.",
  "- Slash commands, the selection toolbar, attachment uploads, and paste/drop all react to their config toggles.",
  "- Preview HTML/CSS is consistent with the current plugins, theme, and syntax theme.",
  "- Output mode shows the full HTML and CSS.",
  "- `blob:` URLs are released on unmount.",
  "- After default-document changes, the storage version is bumped and stale caches refresh defaults while keeping user documents.",
].join("\n");
