// playground/react-playground/app/data/md/react-guide.en.ts
export default [
  "# React Integration Guide",
  "",
  "This guide targets React projects, with the goal of integrating a Mardora editor that matches the React playground in quality: rich Markdown editing, source mode, preview mode, HTML/CSS output, plugin toggles, slash commands, attachment uploads, theme switching, local persistence, and node debugging.",
  "",
  "The React playground wraps CodeMirror with `@uiw/react-codemirror`. You can also create an `EditorView` manually, but if your app already uses React, `@uiw/react-codemirror` removes boilerplate around lifecycle management.",
  "",
  "## 1. Install dependencies",
  "",
  "```shell",
  "npm install mardora",
  "npm install @uiw/react-codemirror",
  "```",
  "",
  "Optional HTML/CSS output panels like the playground also use `@codemirror/lang-html`, `@codemirror/lang-css`, and `@uiw/codemirror-theme-github`; install them only if you keep that panel.",
  "",
  "If you use the Next.js App Router, the editor component must be a client component:",
  "",
  "```tsx",
  '"use client";',
  "```",
  "",
  "## 2. Define content and config",
  "",
  "```tsx",
  'import { useCallback, useEffect, useMemo, useRef, useState } from "react";',
  'import CodeMirror, { ReactCodeMirrorRef } from "@uiw/react-codemirror";',
  'import { githubDark, githubLight } from "@uiw/codemirror-theme-github";',
  'import { html } from "@codemirror/lang-html";',
  'import { css } from "@codemirror/lang-css";',
  'import { EditorView, Extension, mardora, MardoraNode, MardoraPlugin, ThemeEnum } from "mardora/editor";',
  'import { allPlugins } from "mardora/plugins";',
  'import { generateCSS, preview } from "mardora/preview";',
  "",
  "type Content = {",
  "  id: string;",
  "  title: string;",
  "  content: string;",
  "};",
  "",
  'type PlaygroundMode = "live" | "view" | "code" | "output";',
  "type PluginConfig = Record<string, boolean>;",
  "",
  "type PlaygroundConfig = {",
  "  editor: {",
  "    baseStyles: boolean;",
  "    defaultKeybindings: boolean;",
  "    history: boolean;",
  "    indentWithTab: boolean;",
  "    highlightActiveLine: boolean;",
  "    lineWrapping: boolean;",
  "  };",
  "  preview: {",
  "    includeBase: boolean;",
  "    sanitize: boolean;",
  "    contentWidth: \"regular\" | \"wide\";",
  "  };",
  "  features: {",
  "    slashCommands: boolean;",
  "    attachments: boolean;",
  "    pasteDropUploads: boolean;",
  "    selectionToolbar: boolean;",
  "    tableOfContents: boolean;",
  "  };",
  "  plugins: PluginConfig;",
  "};",
  "",
  "const defaultPluginConfig: PluginConfig = Object.fromEntries(",
  "  allPlugins.map((plugin) => [plugin.name.toLowerCase(), true])",
  ");",
  "",
  "const defaultConfig: PlaygroundConfig = {",
  "  editor: {",
  "    baseStyles: true,",
  "    defaultKeybindings: true,",
  "    history: true,",
  "    indentWithTab: true,",
  "    highlightActiveLine: true,",
  "    lineWrapping: true,",
  "  },",
  "  preview: {",
  "    includeBase: true,",
  "    sanitize: true,",
  "    contentWidth: \"regular\",",
  "  },",
  "  features: {",
  "    slashCommands: true,",
  "    attachments: true,",
  "    pasteDropUploads: true,",
  "    selectionToolbar: true,",
  "    tableOfContents: true,",
  "  },",
  "  plugins: defaultPluginConfig,",
  "};",
  "```",
  "",
  "## 3. Organize the default documents",
  "",
  "The React playground uses fixed ids and a version number to refresh the default documents:",
  "",
  "```tsx",
  'const STORAGE_KEY = "mardora-playground-contents";',
  'const STORAGE_CURRENT_KEY = "mardora-playground-current";',
  'const STORAGE_VERSION_KEY = "mardora-playground-version";',
  "const STORAGE_VERSION = 2;",
  "",
  "const DEFAULT_CONTENTS: Content[] = [",
  '  { id: "project-introduction", title: "Project Introduction", content: projectIntroduction },',
  '  { id: "vue2-guide", title: "Vue 2 Integration Guide", content: vue2Guide },',
  '  { id: "vue3-guide", title: "Vue 3 Integration Guide", content: vue3Guide },',
  '  { id: "react-guide", title: "React Integration Guide", content: reactGuide },',
  "];",
  "",
  "const DEFAULT_CONTENT_IDS = new Set(DEFAULT_CONTENTS.map((content) => content.id));",
  "```",
  "",
  "Raise `STORAGE_VERSION` whenever the default documents change. On a version mismatch, replace the fixed-id defaults with the new versions and keep user-created documents.",
  "",
  "## 4. Prepare the uploader and plugin state",
  "",
  "```tsx",
  "export function MardoraReactEditor() {",
  "  const [contents, setContents] = useState<Content[]>(DEFAULT_CONTENTS);",
  "  const [currentContent, setCurrentContent] = useState(0);",
  '  const [mode, setMode] = useState<PlaygroundMode>("live");',
  "  const [config, setConfig] = useState<PlaygroundConfig>(defaultConfig);",
  "  const [nodes, setNodes] = useState<MardoraNode[]>([]);",
  "  const [output, setOutput] = useState<{ html: string; css: string } | null>(null);",
  "  const editor = useRef<ReactCodeMirrorRef>(null);",
  "  const objectUrlsRef = useRef<string[]>([]);",
  "",
  '  const theme = "light";',
  '  const cmTheme = theme === "dark" ? githubDark : githubLight;',
  '  const mardoraTheme = theme === "dark" ? ThemeEnum.DARK : ThemeEnum.LIGHT;',
  "",
  "  const mockUploader = useCallback(async (file: File) => {",
  "    const url = URL.createObjectURL(file);",
  "    objectUrlsRef.current.push(url);",
  "    return {",
  "      url,",
  "      name: file.name,",
  "      mimeType: file.type,",
  "    };",
  "  }, []);",
  "",
  "  const activePlugins = useMemo<MardoraPlugin[]>(() => {",
  "    return allPlugins.filter((plugin) => {",
  "      const name = plugin.name.toLowerCase();",
  "      return config.plugins[name] ?? true;",
  "    });",
  "  }, [config.plugins]);",
  "",
  "  useEffect(() => {",
  "    return () => {",
  "      for (const url of objectUrlsRef.current) {",
  "        URL.revokeObjectURL(url);",
  "      }",
  "      objectUrlsRef.current = [];",
  "    };",
  "  }, []);",
  "}",
  "```",
  "",
  "A production uploader should upload to a back end, object store, or CDN and return a long-lived URL. `blob:` URLs are only suitable for playgrounds or local demos.",
  "",
  "## 5. Create the Mardora extensions",
  "",
  "```tsx",
  "const extensions = useMemo<Extension[]>(",
  "  () =>",
  "    mardora({",
  "      theme: mardoraTheme,",
  "      baseStyles: config.editor.baseStyles,",
  "      contentWidth: config.preview.contentWidth === \"wide\" ? \"full\" : \"default\",",
  "      plugins: activePlugins,",
  "      markdown: [],",
  "      extensions: [],",
  "      keymap: [],",
  '      disableViewPlugin: mode === "code",',
  "      defaultKeybindings: config.editor.defaultKeybindings,",
  "      history: config.editor.history,",
  "      indentWithTab: config.editor.indentWithTab,",
  "      highlightActiveLine: config.editor.highlightActiveLine,",
  "      lineWrapping: config.editor.lineWrapping,",
  "      slashCommands: {",
  "        enabled: config.features.slashCommands,",
  "      },",
  "      selectionToolbar: {",
  "        enabled: config.features.selectionToolbar,",
  "      },",
  "      toc: {",
  '        enabled: mode === "live" && config.features.tableOfContents,',
  "      },",
  "      attachments: {",
  "        enabled: config.features.attachments,",
  "        uploader: config.features.attachments ? mockUploader : undefined,",
  "        enablePaste: config.features.pasteDropUploads,",
  "        enableDrop: config.features.pasteDropUploads,",
  "        accept: {",
  '          image: ["image/*"],',
  '          video: ["video/*"],',
  '          audio: ["audio/*"],',
  '          file: ["*/*"],',
  "        },",
  "      },",
  "      onNodesChange: (nextNodes) => {",
  "        setNodes(nextNodes);",
  "      },",
  "    }),",
  "  [activePlugins, config.editor, config.features, mardoraTheme, mockUploader, mode]",
  ");",
  "```",
  "",
  "The key concern in React is making sure `extensions` only recomputes when the options it actually depends on change. Never put the Markdown text being typed into the `useMemo` deps, or you will trigger needless extension rebuilds.",
  "",
  "## 6. Render the editor",
  "",
  "```tsx",
  "const current = contents[currentContent];",
  "",
  "return (",
  '  <main className="mardora-shell">',
  '    {mode === "view" && output ? (',
  '      <div className="preview-host">',
  "        <style>{output.css}</style>",
  "        <div dangerouslySetInnerHTML={{ __html: output.html }} />",
  "      </div>",
  '    ) : mode === "output" && output ? (',
  '      <div className="output-grid">',
  "        <CodeMirror",
  "          value={output.html}",
  "          theme={cmTheme}",
  "          extensions={[html(), EditorView.lineWrapping, EditorView.editable.of(false)]}",
  "          editable={false}",
  "        />",
  "        <CodeMirror",
  "          value={output.css}",
  "          theme={cmTheme}",
  "          extensions={[css(), EditorView.lineWrapping, EditorView.editable.of(false)]}",
  "          editable={false}",
  "        />",
  "      </div>",
  "    ) : (",
  "      <CodeMirror",
  "        ref={editor}",
  "        value={current.content}",
  "        theme={cmTheme}",
  "        extensions={extensions}",
  "        basicSetup={false}",
  "        onChange={(value) => {",
  "          setContents((items) =>",
  "            items.map((item, index) => (index === currentContent ? { ...item, content: value } : item))",
  "          );",
  "        }}",
  "      />",
  "    )}",
  "  </main>",
  ");",
  "```",
  "",
  "`basicSetup={false}` prevents `@uiw/react-codemirror`'s default capabilities from duplicating the CodeMirror capabilities Mardora assembles itself. When you need extra extensions, add them via `mardora({ extensions: [...] })` or via the outer `extensions={[...extensions, extra]}`.",
  "",
  "## 7. Generate the preview output",
  "",
  "```tsx",
  "useEffect(() => {",
  '  if (!["view", "output"].includes(mode)) return;',
  "",
  "  let cancelled = false;",
  "",
  "  (async () => {",
  '    const markdown = contents[currentContent]?.content || "";',
  "",
  "    const htmlOutput = await preview(markdown, {",
  "      theme: mardoraTheme,",
  "      plugins: activePlugins,",
  "      markdown: [],",
  "      syntaxTheme: cmTheme,",
  "      sanitize: config.preview.sanitize,",
  '      wrapperTag: "div",',
  '      wrapperClass: "mardora-preview",',
  "    });",
  "",
  "    const cssOutput = generateCSS({",
  "      theme: mardoraTheme,",
  "      plugins: activePlugins,",
  '      wrapperClass: "mardora-preview",',
  "      includeBase: config.preview.includeBase,",
  "      syntaxTheme: cmTheme,",
  "    });",
  "",
  "    if (!cancelled) {",
  "      setOutput({ html: htmlOutput, css: cssOutput });",
  "    }",
  "  })();",
  "",
  "  return () => {",
  "    cancelled = true;",
  "  };",
  "}, [activePlugins, cmTheme, config.preview, contents, currentContent, mardoraTheme, mode]);",
  "```",
  "",
  "`preview()` and `generateCSS()` must use the same set of plugins, theme, and syntax theme. Otherwise the edit state, preview state, and output state will diverge visually or in HTML behavior.",
  "",
  "## 8. Local persistence",
  "",
  "```tsx",
  "useEffect(() => {",
  "  const storedContents = localStorage.getItem(STORAGE_KEY);",
  "  const storedCurrent = localStorage.getItem(STORAGE_CURRENT_KEY);",
  "  const storedVersion = localStorage.getItem(STORAGE_VERSION_KEY);",
  "  const isOutdated = storedVersion !== String(STORAGE_VERSION);",
  "",
  "  if (storedContents && !isOutdated) {",
  "    setContents(JSON.parse(storedContents) as Content[]);",
  '    setCurrentContent(Number.parseInt(storedCurrent || "0", 10));',
  "    return;",
  "  }",
  "",
  "  if (storedContents && isOutdated) {",
  "    const parsed = JSON.parse(storedContents) as Content[];",
  "    const userContents = parsed.filter((content) => !DEFAULT_CONTENT_IDS.has(content.id));",
  "    const merged = [...DEFAULT_CONTENTS, ...userContents];",
  "    setContents(merged);",
  "    setCurrentContent(0);",
  "    localStorage.setItem(STORAGE_KEY, JSON.stringify(merged));",
  '    localStorage.setItem(STORAGE_CURRENT_KEY, "0");',
  "    localStorage.setItem(STORAGE_VERSION_KEY, String(STORAGE_VERSION));",
  "    return;",
  "  }",
  "",
  "  localStorage.setItem(STORAGE_KEY, JSON.stringify(DEFAULT_CONTENTS));",
  '  localStorage.setItem(STORAGE_CURRENT_KEY, "0");',
  "  localStorage.setItem(STORAGE_VERSION_KEY, String(STORAGE_VERSION));",
  "}, []);",
  "```",
  "",
  "Debounce saves so you don't write to localStorage on every keystroke.",
  "",
  "## 9. Plugin system",
  "",
  "React integration uses the same `MardoraPlugin`:",
  "",
  "```tsx",
  'import type { DecorationContext } from "mardora/editor";',
  'import { MardoraPlugin } from "mardora/editor";',
  "",
  "class MentionPlugin extends MardoraPlugin {",
  '  readonly name = "mention";',
  '  readonly version = "1.0.0";',
  "",
  "  buildDecorations(ctx: DecorationContext): void {",
  "    // Read ctx.view.state.doc and append Decorations to ctx.decorations.",
  "  }",
  "}",
  "```",
  "",
  "Plugins can override at the same time:",
  "",
  "- `getExtensions()`: add CodeMirror extensions.",
  "- `getMarkdownConfig()`: extend Lezer Markdown grammar.",
  "- `getKeymap()`: add keyboard shortcuts.",
  "- `buildDecorations()`: contribute edit-state decorations.",
  "- `renderToHTML()`: contribute preview HTML.",
  "- `getPreviewStyles()`: contribute preview CSS.",
  "",
  "In your app you can merge custom plugins with the built-in ones:",
  "",
  "```tsx",
  "const plugins = useMemo(() => [...activePlugins, new MentionPlugin()], [activePlugins]);",
  "```",
  "",
  "## 10. Supported API standards",
  "",
  "For React integration, use directly:",
  "",
  "- `mardora/editor`: `mardora()`, `ThemeEnum`, `MardoraPlugin`, `MardoraNode`, TOC/attachment/selection-toolbar types.",
  "- `mardora/plugins`: `allPlugins`, `essentialPlugins`, and individual plugin classes.",
  "- `mardora/preview`: `preview()`, `generateCSS()`, `extractPreviewTocFromMarkdown()`.",
  "- CodeMirror 6: `Extension`, `EditorView`, `EditorState`, `KeyBinding`, `updateListener`.",
  "- Lezer Markdown: plugin-level `MarkdownConfig`.",
  "- React: `useMemo` for extensions, `useEffect` for preview and persistence, `useRef` for editor refs and resource cleanup.",
  "- Browser API: `File`, `FormData`, paste, drop, `URL.createObjectURL`.",
  "",
  "## 11. Acceptance checklist",
  "",
  "- Edit, source, preview, and output modes all switch correctly.",
  "- React state and the CodeMirror value stay in sync two-way, without input lag or rebuild jitter.",
  "- With all `allPlugins` enabled, headings, lists, tables, images, code blocks, math, Mermaid, HTML, and Emoji all render.",
  "- Slash commands, the selection toolbar, attachment uploads, and paste/drop all react to their config toggles.",
  "- Preview HTML/CSS is consistent with the current plugins, theme, and syntax theme.",
  "- Output mode shows the full HTML and CSS.",
  "- `blob:` URLs are released on unmount.",
  "- After default-document changes, the storage version is bumped and stale caches refresh defaults while keeping user documents.",
].join("\n");

// playground/react-playground/app/data/md/vue3-guide.en.ts
export default [
  "# Vue 3 Integration Guide",
  "",
  "This guide targets Vue 3 projects, with the goal of integrating a Mardora editor that matches the Vue 3 playground in quality: rich Markdown editing, source mode, preview mode, HTML/CSS output, plugin toggles, slash commands, attachment uploads, outline, theme switching, and local persistence.",
  "",
  "## 1. Install dependencies",
  "",
  "```shell",
  "npm install mardora",
  "```",
  "",
  "If you also want to display the HTML/CSS output view, install `@codemirror/lang-html`, `@codemirror/lang-css`, and `@uiw/codemirror-theme-github` only for that optional output panel.",
  "",
  "Mardora needs no Vue-3-specific component. The recommended approach is to create the CodeMirror `EditorView` inside `onMounted()` and destroy it in `onBeforeUnmount()`.",
  "",
  "## 2. Prepare state and types",
  "",
  "```ts",
  'import { computed, nextTick, onBeforeUnmount, onMounted, reactive, ref, watch } from "vue";',
  'import { html } from "@codemirror/lang-html";',
  'import { css } from "@codemirror/lang-css";',
  'import { githubDark, githubLight } from "@uiw/codemirror-theme-github";',
  'import type { MardoraNode, MardoraTocItem } from "mardora/editor";',
  'import { EditorState, EditorView, mardora, ThemeEnum } from "mardora/editor";',
  'import { allPlugins } from "mardora/plugins";',
  'import { extractPreviewTocFromMarkdown, generateCSS, preview } from "mardora/preview";',
  "",
  'type PlaygroundMode = "live" | "code" | "view" | "output";',
  'type ThemeMode = "light" | "dark";',
  "type PluginConfig = Record<string, boolean>;",
  "",
  "type PlaygroundConfig = {",
  '  locale: "zh-CN" | "en-US";',
  "  editor: {",
  "    baseStyles: boolean;",
  "    defaultKeybindings: boolean;",
  "    history: boolean;",
  "    indentWithTab: boolean;",
  "    highlightActiveLine: boolean;",
  "    lineWrapping: boolean;",
  "  };",
  "  preview: {",
  "    includeBase: boolean;",
  "    sanitize: boolean;",
  '    contentWidth: "regular" | "wide";',
  "  };",
  "  features: {",
  "    slashCommands: boolean;",
  "    attachments: boolean;",
  "    pasteDropUploads: boolean;",
  "    selectionToolbar: boolean;",
  "    tableOfContents: boolean;",
  "  };",
  "  plugins: PluginConfig;",
  "};",
  "",
  "function createDefaultPluginConfig(): PluginConfig {",
  "  return Object.fromEntries(allPlugins.map((plugin) => [plugin.name.toLowerCase(), true]));",
  "}",
  "",
  "const config = reactive<PlaygroundConfig>({",
  '  locale: "zh-CN",',
  "  editor: {",
  "    baseStyles: true,",
  "    defaultKeybindings: true,",
  "    history: true,",
  "    indentWithTab: true,",
  "    highlightActiveLine: true,",
  "    lineWrapping: true,",
  "  },",
  "  preview: {",
  "    includeBase: true,",
  "    sanitize: true,",
  '    contentWidth: "regular",',
  "  },",
  "  features: {",
  "    slashCommands: true,",
  "    attachments: true,",
  "    pasteDropUploads: true,",
  "    selectionToolbar: true,",
  "    tableOfContents: true,",
  "  },",
  "  plugins: createDefaultPluginConfig(),",
  "});",
  "```",
  "",
  "## 3. Prepare the template",
  "",
  "```vue",
  "<template>",
  '  <section class="mardora-shell">',
  '    <header class="toolbar">',
  "      <button @click=\"mode = 'live'\">Edit</button>",
  "      <button @click=\"mode = 'code'\">Source</button>",
  "      <button @click=\"mode = 'view'\">Preview</button>",
  "      <button @click=\"mode = 'output'\">Output</button>",
  "    </header>",
  "",
  '    <div v-if="mode === \'view\'" ref="previewHost" class="preview-host">',
  '      <div v-html="previewOutput.html" />',
  '      <aside v-if="config.features.tableOfContents" class="preview-toc">',
  "        <button",
  '          v-for="item in previewToc"',
  '          :key="item.id"',
  '          :data-level="item.level"',
  '          :class="{ active: item.active }"',
  '          @click="jumpToc(item)"',
  "        >",
  "          {{ item.text }}",
  "        </button>",
  "      </aside>",
  "    </div>",
  "",
  '    <div v-else-if="mode === \'output\'" class="output-grid">',
  '      <div ref="htmlOutputHost" />',
  '      <div ref="cssOutputHost" />',
  "    </div>",
  "",
  '    <div v-else ref="editorHost" class="editor-host" />',
  "  </section>",
  "</template>",
  "```",
  "",
  "Basic layout:",
  "",
  "```css",
  ".mardora-shell {",
  "  height: 100vh;",
  "  display: flex;",
  "  flex-direction: column;",
  "}",
  "",
  ".editor-host,",
  ".preview-host,",
  ".output-grid {",
  "  flex: 1;",
  "  min-height: 0;",
  "  overflow: auto;",
  "}",
  "",
  ".output-grid {",
  "  display: grid;",
  "  grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);",
  "}",
  "```",
  "",
  "## 4. Create and rebuild the EditorView",
  "",
  "```ts",
  "const editorHost = ref<HTMLElement | null>(null);",
  "const previewHost = ref<HTMLElement | null>(null);",
  "const htmlOutputHost = ref<HTMLElement | null>(null);",
  "const cssOutputHost = ref<HTMLElement | null>(null);",
  "",
  'const mode = ref<PlaygroundMode>("live");',
  'const theme = ref<ThemeMode>("light");',
  'const content = ref("# Hello, Mardora");',
  "const nodes = ref<MardoraNode[]>([]);",
  "const previewToc = ref<MardoraTocItem[]>([]);",
  'const previewOutput = ref({ html: "", css: "" });',
  "",
  "const editorView = ref<EditorView | null>(null);",
  "const htmlView = ref<EditorView | null>(null);",
  "const cssView = ref<EditorView | null>(null);",
  "const previewStyleElement = ref<HTMLStyleElement | null>(null);",
  "const objectUrls: string[] = [];",
  "let internalUpdate = false;",
  "",
  "const activePlugins = computed(() =>",
  "  allPlugins.filter((plugin) => config.plugins[plugin.name.toLowerCase()] !== false)",
  ");",
  "",
  "function cmTheme() {",
  '  return theme.value === "dark" ? githubDark : githubLight;',
  "}",
  "",
  "function mardoraTheme() {",
  '  return theme.value === "dark" ? ThemeEnum.DARK : ThemeEnum.LIGHT;',
  "}",
  "",
  "async function mockUploader(file: File) {",
  "  const url = URL.createObjectURL(file);",
  "  objectUrls.push(url);",
  "  return {",
  "    url,",
  "    name: file.name,",
  "    mimeType: file.type,",
  "  };",
  "}",
  "",
  "function createEditorView() {",
  "  const parent = editorHost.value;",
  "  if (!parent) return;",
  "",
  "  const updateListener = EditorView.updateListener.of((update) => {",
  "    if (!update.docChanged || internalUpdate) return;",
  "    content.value = update.state.doc.toString();",
  "  });",
  "",
  "  editorView.value = new EditorView({",
  "    parent,",
  "    state: EditorState.create({",
  "      doc: content.value,",
  "      extensions: [",
  "        cmTheme(),",
  "        mardora({",
  "          theme: mardoraTheme(),",
  "          locale: config.locale,",
  "          baseStyles: config.editor.baseStyles,",
  "          contentWidth: config.preview.contentWidth === \"wide\" ? \"full\" : \"default\",",
  "          plugins: activePlugins.value,",
  "          markdown: [],",
  "          extensions: [],",
  "          keymap: [],",
  '          disableViewPlugin: mode.value === "code",',
  "          defaultKeybindings: config.editor.defaultKeybindings,",
  "          history: config.editor.history,",
  "          indentWithTab: config.editor.indentWithTab,",
  "          highlightActiveLine: config.editor.highlightActiveLine,",
  "          lineWrapping: config.editor.lineWrapping,",
  "          slashCommands: {",
  "            enabled: config.features.slashCommands,",
  "          },",
  "          selectionToolbar: {",
  "            enabled: config.features.selectionToolbar,",
  "          },",
  "          toc: {",
  '            enabled: mode.value === "live" && config.features.tableOfContents,',
  "            onTocChange: (items) => {",
  "              previewToc.value = items;",
  "            },",
  "          },",
  "          attachments: {",
  "            enabled: config.features.attachments,",
  "            uploader: config.features.attachments ? mockUploader : undefined,",
  "            enablePaste: config.features.pasteDropUploads,",
  "            enableDrop: config.features.pasteDropUploads,",
  "            accept: {",
  '              image: ["image/*"],',
  '              video: ["video/*"],',
  '              audio: ["audio/*"],',
  '              file: ["*/*"],',
  "            },",
  "          },",
  "          onNodesChange: (nextNodes) => {",
  "            nodes.value = nextNodes;",
  "          },",
  "        }),",
  "        updateListener,",
  "      ],",
  "    }),",
  "  });",
  "}",
  "```",
  "",
  "## 5. Render preview and output",
  "",
  "```ts",
  "async function renderPreview() {",
  "  const syntaxTheme = cmTheme();",
  "",
  "  const htmlOutput = await preview(content.value, {",
  "    theme: mardoraTheme(),",
  "    plugins: activePlugins.value,",
  "    markdown: [],",
  "    syntaxTheme,",
  "    sanitize: config.preview.sanitize,",
  '    wrapperTag: "div",',
  '    wrapperClass: "mardora-preview vue3-preview",',
  "  });",
  "",
  "  const cssOutput = generateCSS({",
  "    theme: mardoraTheme(),",
  "    plugins: activePlugins.value,",
  '    wrapperClass: "mardora-preview",',
  "    includeBase: config.preview.includeBase,",
  "    syntaxTheme,",
  "  });",
  "",
  "  previewOutput.value = { html: htmlOutput, css: cssOutput };",
  "  previewToc.value = extractPreviewTocFromMarkdown(content.value);",
  "",
  "  await nextTick();",
  "",
  '  if (mode.value === "view") {',
  "    updatePreviewStyles();",
  "  }",
  "",
  '  if (mode.value === "output") {',
  "    createOutputViews();",
  "  }",
  "}",
  "",
  "function updatePreviewStyles() {",
  "  if (!previewHost.value) return;",
  "",
  "  if (!previewStyleElement.value) {",
  '    previewStyleElement.value = document.createElement("style");',
  "    previewHost.value.prepend(previewStyleElement.value);",
  "  }",
  "",
  "  previewStyleElement.value.textContent = previewOutput.value.css;",
  "}",
  "",
  "function createOutputViews() {",
  "  if (!htmlOutputHost.value || !cssOutputHost.value) return;",
  "",
  "  htmlView.value = new EditorView({",
  "    parent: htmlOutputHost.value,",
  "    state: EditorState.create({",
  "      doc: previewOutput.value.html,",
  "      extensions: [cmTheme(), html(), EditorView.lineWrapping, EditorState.readOnly.of(true)],",
  "    }),",
  "  });",
  "",
  "  cssView.value = new EditorView({",
  "    parent: cssOutputHost.value,",
  "    state: EditorState.create({",
  "      doc: previewOutput.value.css,",
  "      extensions: [cmTheme(), css(), EditorView.lineWrapping, EditorState.readOnly.of(true)],",
  "    }),",
  "  });",
  "}",
  "```",
  "",
  "## 6. Watch mode and config changes",
  "",
  "```ts",
  "async function rebuildForMode() {",
  "  await nextTick();",
  "  destroyViews();",
  "",
  '  if (mode.value === "view" || mode.value === "output") {',
  "    await renderPreview();",
  "    return;",
  "  }",
  "",
  "  createEditorView();",
  "}",
  "",
  "watch([mode, theme, activePlugins], () => {",
  "  rebuildForMode();",
  "});",
  "",
  "watch(",
  "  config,",
  "  () => {",
  "    rebuildForMode();",
  "  },",
  "  { deep: true }",
  ");",
  "",
  "watch(content, (next) => {",
  "  if (!editorView.value) return;",
  "  if (next === editorView.value.state.doc.toString()) return;",
  "",
  "  internalUpdate = true;",
  "  editorView.value.dispatch({",
  "    changes: {",
  "      from: 0,",
  "      to: editorView.value.state.doc.length,",
  "      insert: next,",
  "    },",
  "  });",
  "  internalUpdate = false;",
  "});",
  "",
  "onMounted(() => {",
  "  rebuildForMode();",
  "});",
  "```",
  "",
  "Note: do not rebuild the `EditorView` on every keystroke. Rebuild only on mode, theme, plugin, or config changes; sync body changes via dispatch.",
  "",
  "## 7. Outline jumping",
  "",
  "```ts",
  "function jumpToc(item: MardoraTocItem) {",
  '  if (mode.value === "view") {',
  "    const target = previewHost.value?.querySelector(`#${CSS.escape(item.id)}`) as HTMLElement | null;",
  '    target?.scrollIntoView({ block: "start" });',
  "    return;",
  "  }",
  "",
  '  if (editorView.value && typeof item.from === "number") {',
  "    editorView.value.dispatch({",
  "      selection: { anchor: item.from },",
  '      effects: EditorView.scrollIntoView(item.from, { y: "start" }),',
  "    });",
  "    editorView.value.focus();",
  "  }",
  "}",
  "```",
  "",
  "The edit-state outline comes from `toc.onTocChange`; the preview-state outline comes from `extractPreviewTocFromMarkdown()`. This way the outline works whether or not an editor instance exists.",
  "",
  "## 8. Lifecycle cleanup",
  "",
  "```ts",
  "function destroyViews() {",
  "  editorView.value?.destroy();",
  "  htmlView.value?.destroy();",
  "  cssView.value?.destroy();",
  "",
  "  editorView.value = null;",
  "  htmlView.value = null;",
  "  cssView.value = null;",
  "",
  "  if (previewStyleElement.value) {",
  "    previewStyleElement.value.remove();",
  "    previewStyleElement.value = null;",
  "  }",
  "}",
  "",
  "onBeforeUnmount(() => {",
  "  destroyViews();",
  "  for (const url of objectUrls) {",
  "    URL.revokeObjectURL(url);",
  "  }",
  "  objectUrls.length = 0;",
  "});",
  "```",
  "",
  "## 9. Local document data",
  "",
  "Give default documents fixed ids and refresh them by version number:",
  "",
  "```ts",
  "export type Content = {",
  "  id: string;",
  "  title: string;",
  "  content: string;",
  "};",
  "",
  "export const STORAGE_VERSION = 2;",
  "",
  "export const defaultContents: Content[] = [",
  '  { id: "project-introduction", title: "Project Introduction", content: projectIntroduction },',
  '  { id: "vue2-guide", title: "Vue 2 Integration Guide", content: vue2Guide },',
  '  { id: "vue3-guide", title: "Vue 3 Integration Guide", content: vue3Guide },',
  '  { id: "react-guide", title: "React Integration Guide", content: reactGuide },',
  "];",
  "```",
  "",
  "When refreshing default documents, replace only these fixed ids; user-created documents should be preserved.",
  "",
  "## 10. Plugins and API standards",
  "",
  "Vue 3 integration uses Mardora's standard API directly:",
  "",
  "- `mardora/editor`: editor extensions, `ThemeEnum`, `MardoraNode`, `MardoraTocItem`.",
  "- `mardora/plugins`: `allPlugins`, `essentialPlugins`, and individual plugin classes.",
  "- `mardora/preview`: `preview()`, `generateCSS()`, `extractPreviewTocFromMarkdown()`.",
  "- CodeMirror 6: `EditorState`, `EditorView`, `Extension`, `updateListener`, `EditorView.lineWrapping`.",
  "- Lezer Markdown: extend grammar via plugin `getMarkdownConfig()`.",
  "- Browser API: attachment uploads use `File`, `FormData`, paste, drop.",
  "",
  "## 11. Acceptance checklist",
  "",
  "- Edit, source, preview, and output modes all switch correctly.",
  "- Vue 3 ref/reactive state and the CodeMirror document never overwrite each other or loop.",
  "- With all `allPlugins` enabled, headings, lists, tables, images, code blocks, math, Mermaid, HTML, and Emoji all render.",
  "- Slash commands, the selection toolbar, attachment uploads, paste/drop, and the outline all react to their config toggles.",
  "- `preview()` and `generateCSS()` use the same set of plugins, theme, and syntax theme.",
  "- On unmount, all `EditorView`s are destroyed and `blob:` URLs released.",
  "- After default-document changes, the storage version is bumped and stale caches refresh.",
].join("\n");
