// apps/web/app/playground/devbar.tsx
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@workspace/ui/components/accordion";
import { Switch } from "@workspace/ui/components/switch";
import { Label } from "@workspace/ui/components/label";
import { allPlugins, DraftlyNode } from "draftly/src";
import React from "react";
import { PlaygroundConfig } from "./page";

type Props = {
  setShowNodes: (show: boolean) => void;
  nodes: DraftlyNode[];
  config: PlaygroundConfig;
  setConfig: React.Dispatch<React.SetStateAction<PlaygroundConfig>>;
  outputTime?: number | null;
};

export default function Devbar({ setShowNodes, nodes, config, setConfig, outputTime }: Props) {
  // Helper to toggle editor config
  const toggleEditorOption = (key: keyof PlaygroundConfig["editor"]) => {
    setConfig((prev) => ({
      ...prev,
      editor: { ...prev.editor, [key]: !prev.editor[key] },
    }));
  };

  // Helper to toggle preview config
  const togglePreviewOption = (key: keyof PlaygroundConfig["preview"]) => {
    setConfig((prev) => ({
      ...prev,
      preview: { ...prev.preview, [key]: !prev.preview[key] },
    }));
  };

  // Helper to toggle Draftly feature config
  const toggleFeatureOption = (key: keyof PlaygroundConfig["features"]) => {
    setConfig((prev) => ({
      ...prev,
      features: { ...prev.features, [key]: !prev.features[key] },
    }));
  };

  // Helper to toggle plugin
  const togglePlugin = (key: keyof PlaygroundConfig["plugins"]) => {
    setConfig((prev) => ({
      ...prev,
      plugins: { ...prev.plugins, [key]: !prev.plugins[key] },
    }));
  };

  // Track which accordions are open
  const [openValues, setOpenValues] = React.useState<string[]>(["editor", "preview"]);
  const isNodesOpen = openValues.includes("nodes");

  const handleValueChange = (values: string[]) => {
    // If nodes is being opened, collapse everything else
    if (values.includes("nodes") && !openValues.includes("nodes")) {
      setOpenValues(["nodes"]);
      setShowNodes(true);
    } else if (!values.includes("nodes") && openValues.includes("nodes")) {
      // Nodes is being closed, restore other sections
      setOpenValues(values.length > 0 ? values : ["editor", "preview"]);
      setShowNodes(false);
    } else {
      setOpenValues(values.filter((v) => v !== "nodes"));
      setShowNodes(values.includes("nodes"));
    }
  };

  return (
    <div className="h-full w-full flex flex-col border rounded-lg">
      <div className="text-muted-foreground font-mono text-center whitespace-nowrap h-10 p-2 border-b shrink-0">
        Developer Panel
      </div>

      {outputTime !== null && (
        <div className="text-xs text-muted-foreground p-2 border-b">
          Output generated in {outputTime?.toFixed(2)}ms
        </div>
      )}

      <div className="flex-1 overflow-y-auto min-h-0">
        <Accordion
          type="multiple"
          value={openValues}
          className={`w-full ${isNodesOpen ? "h-full flex flex-col" : ""}`}
          onValueChange={handleValueChange}
        >
          {/* Editor Options */}
          <AccordionItem value="editor">
            <AccordionTrigger className="p-2 border-b rounded-none hover:no-underline cursor-pointer hover:bg-accent hover:text-accent-foreground">
              Editor Options
            </AccordionTrigger>
            <AccordionContent className="p-3 space-y-3">
              <ConfigSwitch
                id="baseStyles"
                label="Base Styles"
                description="Include default editor styles"
                checked={config.editor.baseStyles}
                onCheckedChange={() => toggleEditorOption("baseStyles")}
              />
              <ConfigSwitch
                id="defaultKeybindings"
                label="Default Keybindings"
                description="Enable standard keyboard shortcuts"
                checked={config.editor.defaultKeybindings}
                onCheckedChange={() => toggleEditorOption("defaultKeybindings")}
              />
              <ConfigSwitch
                id="history"
                label="History"
                description="Enable undo/redo support"
                checked={config.editor.history}
                onCheckedChange={() => toggleEditorOption("history")}
              />
              <ConfigSwitch
                id="indentWithTab"
                label="Indent with Tab"
                description="Use Tab key for indentation"
                checked={config.editor.indentWithTab}
                onCheckedChange={() => toggleEditorOption("indentWithTab")}
              />
              <ConfigSwitch
                id="highlightActiveLine"
                label="Highlight Active Line"
                description="Highlight the current line"
                checked={config.editor.highlightActiveLine}
                onCheckedChange={() => toggleEditorOption("highlightActiveLine")}
              />
              <ConfigSwitch
                id="lineWrapping"
                label="Line Wrapping"
                description="Wrap long lines"
                checked={config.editor.lineWrapping}
                onCheckedChange={() => toggleEditorOption("lineWrapping")}
              />
            </AccordionContent>
          </AccordionItem>

          {/* Preview Options */}
          <AccordionItem value="preview">
            <AccordionTrigger className="p-2 border-b rounded-none hover:no-underline cursor-pointer hover:bg-accent hover:text-accent-foreground">
              Preview Options
            </AccordionTrigger>
            <AccordionContent className="p-3 space-y-3">
              <ConfigSwitch
                id="includeBase"
                label="Include Base CSS"
                description="Include base preview styles"
                checked={config.preview.includeBase}
                onCheckedChange={() => togglePreviewOption("includeBase")}
              />
              <ConfigSwitch
                id="sanitize"
                label="Sanitize HTML"
                description="Sanitize HTML output for security"
                checked={config.preview.sanitize}
                onCheckedChange={() => togglePreviewOption("sanitize")}
              />
            </AccordionContent>
          </AccordionItem>

          {/* Feature Options */}
          <AccordionItem value="features">
            <AccordionTrigger className="p-2 border-b rounded-none hover:no-underline cursor-pointer hover:bg-accent hover:text-accent-foreground">
              Feature Options
            </AccordionTrigger>
            <AccordionContent className="p-3 space-y-3">
              <ConfigSwitch
                id="slashCommands"
                label="Slash Commands"
                description="Open the command menu with line-start slash input"
                checked={config.features.slashCommands}
                onCheckedChange={() => toggleFeatureOption("slashCommands")}
              />
              <ConfigSwitch
                id="attachments"
                label="Attachments"
                description="Enable local file selection through media commands"
                checked={config.features.attachments}
                onCheckedChange={() => toggleFeatureOption("attachments")}
              />
              <ConfigSwitch
                id="pasteDropUploads"
                label="Paste/Drop Uploads"
                description="Upload pasted or dropped files with the mock uploader"
                checked={config.features.pasteDropUploads}
                onCheckedChange={() => toggleFeatureOption("pasteDropUploads")}
              />
            </AccordionContent>
          </AccordionItem>

          {/* Plugin Toggles */}
          <AccordionItem value="plugins">
            <AccordionTrigger className="p-2 border-b rounded-none hover:no-underline cursor-pointer hover:bg-accent hover:text-accent-foreground">
              Plugins
            </AccordionTrigger>
            <AccordionContent className="p-3 space-y-3">
              {allPlugins.map((plugin) => {
                const key = plugin.name.toLowerCase();
                return (
                  <ConfigSwitch
                    key={key}
                    id={key}
                    label={plugin.name}
                    description={`Enable ${plugin.name} plugin`}
                    checked={config.plugins[key] ?? true}
                    onCheckedChange={() => togglePlugin(key)}
                  />
                );
              })}
            </AccordionContent>
          </AccordionItem>

          {/* Nodes Viewer */}
          <AccordionItem value="nodes" className={"flex-1 flex flex-col min-h-0"}>
            <AccordionTrigger className="p-2 border-b rounded-none hover:no-underline cursor-pointer hover:bg-accent hover:text-accent-foreground shrink-0">
              <div>
                Nodes <span className="text-muted-foreground text-xs">(Hide for performance)</span>
              </div>
            </AccordionTrigger>
            <AccordionContent className={"flex-1 h-full overflow-auto p-0"}>
              <NodeViewer nodes={nodes} />
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </div>
  );
}

// Reusable switch component with label and description
function ConfigSwitch({
  id,
  label,
  description,
  checked,
  onCheckedChange,
}: {
  id: string;
  label: string;
  description: string;
  checked: boolean;
  onCheckedChange: () => void;
}) {
  return (
    <div className="flex items-center justify-between gap-2">
      <div className="flex flex-col gap-0.5">
        <Label htmlFor={id} className="text-sm font-medium cursor-pointer">
          {label}
        </Label>
        <span className="text-xs text-muted-foreground">{description}</span>
      </div>
      <Switch id={id} checked={checked} onCheckedChange={onCheckedChange} />
    </div>
  );
}

function NodeViewer({ nodes, depth = 0 }: { nodes: DraftlyNode[]; depth?: number }) {
  return (
    <div className="font-mono text-xs">
      {nodes.map((node, idx) => (
        <div key={`${node.name}-${node.from}-${idx}`}>
          <div
            className={`flex items-center gap-2 py-0.5 px-1 rounded ${node.isSelected ? "bg-primary/20 text-primary" : "hover:bg-muted"}`}
            style={{ paddingLeft: `${depth * 12 + 4}px` }}
          >
            <span className="font-semibold">{node.name}</span>
            <span className="text-muted-foreground">
              [{node.from}:{node.to}]
            </span>
          </div>
          {node.children.length > 0 && <NodeViewer nodes={node.children} depth={depth + 1} />}
        </div>
      ))}
    </div>
  );
}

// playground/vue2-playground/src/components/playground/Devbar.vue
<template>
  <aside class="devbar-content">
    <div class="devbar-title">Developer Panel</div>
    <div v-if="outputTime !== null" class="output-time">Output generated in {{ outputLabel }}</div>

    <div class="accordion">
      <section class="accordion-item">
        <button class="accordion-trigger" type="button" @click="toggleSection('editor')">
          <span>Editor Options</span>
          <span class="chevron" aria-hidden="true">{{ isOpen("editor") ? "^" : "v" }}</span>
        </button>
        <div v-if="isOpen('editor')" class="accordion-content">
          <label v-for="item in editorOptions" :key="item.key" class="switch-row">
            <span class="switch-copy">
              <span class="switch-label">{{ item.label }}</span>
              <span class="switch-description">{{ item.description }}</span>
            </span>
            <input
              class="switch-input"
              type="checkbox"
              :checked="config.editor[item.key]"
              @change="updateEditorOption(item.key, $event)"
            />
            <span class="switch-control" aria-hidden="true" />
          </label>
        </div>
      </section>

      <section class="accordion-item">
        <button class="accordion-trigger" type="button" @click="toggleSection('preview')">
          <span>Preview Options</span>
          <span class="chevron" aria-hidden="true">{{ isOpen("preview") ? "^" : "v" }}</span>
        </button>
        <div v-if="isOpen('preview')" class="accordion-content">
          <label class="switch-row">
            <span class="switch-copy">
              <span class="switch-label">Include Base CSS</span>
              <span class="switch-description">Include base preview styles</span>
            </span>
            <input class="switch-input" type="checkbox" :checked="config.preview.includeBase" @change="updatePreviewOption('includeBase', $event)" />
            <span class="switch-control" aria-hidden="true" />
          </label>
          <label class="switch-row">
            <span class="switch-copy">
              <span class="switch-label">Sanitize HTML</span>
              <span class="switch-description">Sanitize HTML output for security</span>
            </span>
            <input class="switch-input" type="checkbox" :checked="config.preview.sanitize" @change="updatePreviewOption('sanitize', $event)" />
            <span class="switch-control" aria-hidden="true" />
          </label>
          <div class="option-row">
            <span class="switch-copy">
              <span class="switch-label">Content Width</span>
              <span class="switch-description">Adjust Live and View content width</span>
            </span>
            <div class="segmented-control" role="group" aria-label="Content width">
              <button
                v-for="item in contentWidthOptions"
                :key="item.value"
                type="button"
                class="segmented-control-button"
                :class="{ 'segmented-control-button-active': config.preview.contentWidth === item.value }"
                @click="updateContentWidth(item.value)"
              >
                {{ item.label }}
              </button>
            </div>
          </div>
          <div class="option-row">
            <span class="switch-copy">
              <span class="switch-label">Language</span>
              <span class="switch-description">Adjust Draftly-owned editor UI text</span>
            </span>
            <div class="segmented-control" role="group" aria-label="Language">
              <button
                v-for="item in localeOptions"
                :key="item.value"
                type="button"
                class="segmented-control-button"
                :class="{ 'segmented-control-button-active': config.locale === item.value }"
                @click="updateLocale(item.value)"
              >
                {{ item.label }}
              </button>
            </div>
          </div>
        </div>
      </section>

      <section class="accordion-item">
        <button class="accordion-trigger" type="button" @click="toggleSection('features')">
          <span>Feature Options</span>
          <span class="chevron" aria-hidden="true">{{ isOpen("features") ? "^" : "v" }}</span>
        </button>
        <div v-if="isOpen('features')" class="accordion-content">
          <label v-for="item in featureOptions" :key="item.key" class="switch-row">
            <span class="switch-copy">
              <span class="switch-label">{{ item.label }}</span>
              <span class="switch-description">{{ item.description }}</span>
            </span>
            <input
              class="switch-input"
              type="checkbox"
              :checked="config.features[item.key]"
              @change="updateFeatureOption(item.key, $event)"
            />
            <span class="switch-control" aria-hidden="true" />
          </label>
        </div>
      </section>

      <section class="accordion-item">
        <button class="accordion-trigger" type="button" @click="toggleSection('plugins')">
          <span>Plugins</span>
          <span class="chevron" aria-hidden="true">{{ isOpen("plugins") ? "^" : "v" }}</span>
        </button>
        <div v-if="isOpen('plugins')" class="accordion-content">
          <label v-for="name in pluginNames" :key="name" class="switch-row">
            <span class="switch-copy">
              <span class="switch-label">{{ name }}</span>
              <span class="switch-description">Enable {{ name }} plugin</span>
            </span>
            <input class="switch-input" type="checkbox" :checked="config.plugins[name]" @change="updatePlugin(name, $event)" />
            <span class="switch-control" aria-hidden="true" />
          </label>
        </div>
      </section>

      <section class="accordion-item nodes-section" :class="{ 'nodes-section-open': isOpen('nodes') }">
        <button class="accordion-trigger" type="button" @click="toggleNodes">
          <span>Nodes <small>(Hide for performance)</small></span>
          <span class="chevron" aria-hidden="true">{{ isOpen("nodes") ? "^" : "v" }}</span>
        </button>
        <div v-if="isOpen('nodes')" class="accordion-content node-content">
          <pre class="node-list">{{ formattedNodes }}</pre>
        </div>
      </section>
    </div>
  </aside>
</template>

<script lang="ts">
import Vue from "vue";
import type { DraftlyNode } from "draftly/editor";
import type { PlaygroundConfig, PlaygroundLocale, PreviewContentWidth } from "@/types";

type EditorOptionKey = keyof PlaygroundConfig["editor"];
type PreviewOptionKey = "includeBase" | "sanitize";
type FeatureOptionKey = keyof PlaygroundConfig["features"];

function cloneConfig(config: PlaygroundConfig): PlaygroundConfig {
  return JSON.parse(JSON.stringify(config)) as PlaygroundConfig;
}

export default Vue.extend({
  name: "PlaygroundDevbar",
  props: {
    config: {
      type: Object as () => PlaygroundConfig,
      required: true,
    },
    showNodes: {
      type: Boolean,
      required: true,
    },
    nodes: {
      type: Array as () => DraftlyNode[],
      required: true,
    },
    outputTime: {
      type: Number,
      default: null,
    },
  },
  data() {
    return {
      openSections: ["editor", "preview"] as string[],
      editorOptions: [
        { key: "baseStyles" as EditorOptionKey, label: "Base Styles", description: "Include default editor styles" },
        { key: "defaultKeybindings" as EditorOptionKey, label: "Default Keybindings", description: "Enable standard keyboard shortcuts" },
        { key: "history" as EditorOptionKey, label: "History", description: "Enable undo/redo support" },
        { key: "indentWithTab" as EditorOptionKey, label: "Indent with Tab", description: "Use Tab key for indentation" },
        { key: "highlightActiveLine" as EditorOptionKey, label: "Highlight Active Line", description: "Highlight the current line" },
        { key: "lineWrapping" as EditorOptionKey, label: "Line Wrapping", description: "Wrap long lines" },
      ],
      featureOptions: [
        { key: "slashCommands" as FeatureOptionKey, label: "Slash Commands", description: "Open the command menu with line-start slash input" },
        { key: "attachments" as FeatureOptionKey, label: "Attachments", description: "Enable local file selection through media commands" },
        { key: "pasteDropUploads" as FeatureOptionKey, label: "Paste/Drop Uploads", description: "Upload pasted or dropped files with the mock uploader" },
        { key: "tableOfContents" as FeatureOptionKey, label: "Table of Contents", description: "Show the built-in right-side document outline" },
      ],
      contentWidthOptions: [
        { value: "regular" as PreviewContentWidth, label: "Regular" },
        { value: "wide" as PreviewContentWidth, label: "Wide" },
      ],
      localeOptions: [
        { value: "zh-CN" as PlaygroundLocale, label: "中文" },
        { value: "en-US" as PlaygroundLocale, label: "English" },
      ],
    };
  },
  computed: {
    pluginNames(): string[] {
      return Object.keys(this.config.plugins);
    },
    formattedNodes(): string {
      return JSON.stringify(this.nodes, null, 2);
    },
    outputLabel(): string {
      return typeof this.outputTime === "number" ? `${this.outputTime.toFixed(1)}ms` : "n/a";
    },
  },
  methods: {
    isOpen(section: string): boolean {
      return this.openSections.includes(section);
    },
    toggleSection(section: string) {
      this.openSections = this.isOpen(section)
        ? this.openSections.filter((item) => item !== section)
        : [...this.openSections, section];
    },
    toggleNodes() {
      if (this.isOpen("nodes")) {
        this.openSections = this.openSections.filter((item) => item !== "nodes");
        this.$emit("update-show-nodes", false);
      } else {
        this.openSections = ["nodes"];
        this.$emit("update-show-nodes", true);
      }
    },
    eventChecked(event: Event): boolean {
      return (event.target as HTMLInputElement).checked;
    },
    updateEditorOption(key: EditorOptionKey, event: Event) {
      const nextConfig = cloneConfig(this.config);
      nextConfig.editor[key] = this.eventChecked(event);
      this.$emit("update-config", nextConfig);
    },
    updatePreviewOption(key: PreviewOptionKey, event: Event) {
      const nextConfig = cloneConfig(this.config);
      nextConfig.preview[key] = this.eventChecked(event);
      this.$emit("update-config", nextConfig);
    },
    updateContentWidth(value: PreviewContentWidth) {
      const nextConfig = cloneConfig(this.config);
      nextConfig.preview.contentWidth = value;
      this.$emit("update-config", nextConfig);
    },
    updateLocale(value: PlaygroundLocale) {
      const nextConfig = cloneConfig(this.config);
      nextConfig.locale = value;
      this.$emit("update-config", nextConfig);
    },
    updateFeatureOption(key: FeatureOptionKey, event: Event) {
      const nextConfig = cloneConfig(this.config);
      nextConfig.features[key] = this.eventChecked(event);
      this.$emit("update-config", nextConfig);
    },
    updatePlugin(name: string, event: Event) {
      const nextConfig = cloneConfig(this.config);
      nextConfig.plugins[name] = this.eventChecked(event);
      this.$emit("update-config", nextConfig);
    },
    updateShowNodes(event: Event) {
      this.$emit("update-show-nodes", this.eventChecked(event));
    },
  },
});
</script>
