// playground/react-playground/app/data/md/vue3-guide.ts
export default [
  "# Vue3 接入指南",
  "",
  "本文面向 Vue 3 项目，目标是用 Composition API 接入一个与 Mardora Vue 3 playground 同等质量的编辑器：支持富 Markdown 编辑、源码模式、预览模式、HTML/CSS 输出、插件开关、slash commands、附件上传、选区工具栏、目录、主题切换和本地持久化。",
  "",
  "## 1. Vue 3 接入结论",
  "",
  "| 项目     | 建议                                                                   |",
  "| -------- | ---------------------------------------------------------------------- |",
  "| 接入方式 | 在组件中通过 `ref<HTMLElement>()` 挂载 CodeMirror `EditorView`。       |",
  "| 生命周期 | `onMounted()` 创建，`onBeforeUnmount()` 销毁。                         |",
  "| 状态管理 | Markdown 原文放在 `ref` 或业务 store 中。                              |",
  "| 预览     | 使用 `preview()`、`generateCSS()`、`extractPreviewTocFromMarkdown()`。 |",
  "| 配置更新 | 主题、模式、插件、功能开关变化时重建 `EditorView`。                    |",
  "| 输入同步 | 正文输入只更新 Markdown state，不重建扩展。                            |",
  "",
  "## 2. 安装依赖",
  "",
  "```shell",
  "npm install mardora",
  "```",
  "",
  "下面的 HTML/CSS 输出面板示例会用到 `@codemirror/lang-html`、`@codemirror/lang-css` 和 `@uiw/codemirror-theme-github`；只有保留该面板时才需要按需安装。",
  "",
  "Mardora 不提供 Vue 3 组件封装。直接使用 CodeMirror 6 API 更可控，也更接近 playground。",
  "",
  "## 3. 模板结构",
  "",
  "```vue",
  "<template>",
  '  <section class="mardora-vue3-shell">',
  '    <header class="mardora-toolbar">',
  '      <button type="button" @click="mode = \'live\'">编辑</button>',
  '      <button type="button" @click="mode = \'code\'">源码</button>',
  '      <button type="button" @click="mode = \'view\'">预览</button>',
  '      <button type="button" @click="mode = \'output\'">输出</button>',
  "    </header>",
  "",
  '    <div v-if="mode === \'view\'" ref="previewHost" class="mardora-preview-host">',
  '      <div v-html="previewOutput.html" />',
  "",
  '      <aside v-if="config.features.tableOfContents" class="mardora-preview-toc">',
  "        <button",
  '          v-for="item in previewToc"',
  '          :key="item.id"',
  '          type="button"',
  '          :data-level="item.level"',
  '          :class="{ active: item.active }"',
  '          @click="jumpToc(item)"',
  "        >",
  "          {{ item.text }}",
  "        </button>",
  "      </aside>",
  "    </div>",
  "",
  '    <div v-else-if="mode === \'output\'" class="mardora-output-grid">',
  '      <div ref="htmlOutputHost" />',
  '      <div ref="cssOutputHost" />',
  "    </div>",
  "",
  '    <div v-else ref="editorHost" class="mardora-editor-host" />',
  "  </section>",
  "</template>",
  "```",
  "",
  "```css",
  ".mardora-vue3-shell {",
  "  display: flex;",
  "  flex-direction: column;",
  "  height: 100vh;",
  "}",
  "",
  ".mardora-editor-host,",
  ".mardora-preview-host,",
  ".mardora-output-grid {",
  "  flex: 1;",
  "  min-height: 0;",
  "  overflow: auto;",
  "}",
  "",
  ".mardora-output-grid {",
  "  display: grid;",
  "  grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);",
  "}",
  "```",
  "",
  "## 4. 状态和配置",
  "",
  "```ts",
  'import { computed, nextTick, onBeforeUnmount, onMounted, reactive, ref, watch } from "vue";',
  'import { html } from "@codemirror/lang-html";',
  'import { css } from "@codemirror/lang-css";',
  'import { githubDark, githubLight } from "@uiw/codemirror-theme-github";',
  'import type { MardoraAttachmentUploadContext, MardoraNode, MardoraTocItem } from "mardora/editor";',
  'import { EditorState, EditorView, mardora, ThemeEnum } from "mardora/editor";',
  'import { allPlugins } from "mardora/plugins";',
  'import { extractPreviewTocFromMarkdown, generateCSS, preview } from "mardora/preview";',
  "",
  'type Mode = "live" | "code" | "view" | "output";',
  "type PluginConfig = Record<string, boolean>;",
  "",
  "const editorHost = ref<HTMLElement | null>(null);",
  "const previewHost = ref<HTMLElement | null>(null);",
  "const htmlOutputHost = ref<HTMLElement | null>(null);",
  "const cssOutputHost = ref<HTMLElement | null>(null);",
  "",
  'const mode = ref<Mode>("live");',
  'const theme = ref<"light" | "dark">("light");',
  'const content = ref("# Hello, Mardora");',
  "const nodes = ref<MardoraNode[]>([]);",
  "const previewToc = ref<MardoraTocItem[]>([]);",
  'const previewOutput = ref({ html: "", css: "" });',
  "",
  "const editorView = ref<EditorView | null>(null);",
  "const htmlView = ref<EditorView | null>(null);",
  "const cssView = ref<EditorView | null>(null);",
  "const previewStyleElement = ref<HTMLStyleElement | null>(null);",
  "const objectUrls: string[] = [];",
  "",
  "let internalUpdate = false;",
  "",
  "const config = reactive({",
  '  locale: "zh-CN" as "zh-CN" | "en-US",',
  "  editor: {",
  "    baseStyles: true,",
  "    defaultKeybindings: true,",
  "    history: true,",
  "    indentWithTab: true,",
  "    highlightActiveLine: true,",
  "    lineWrapping: true,",
  "  },",
  "  preview: {",
  "    includeBase: true,",
  "    sanitize: true,",
  "  },",
  "  features: {",
  "    slashCommands: true,",
  "    attachments: true,",
  "    pasteDropUploads: true,",
  "    selectionToolbar: true,",
  "    tableOfContents: true,",
  "  },",
  "  plugins: Object.fromEntries(allPlugins.map((plugin) => [plugin.name.toLowerCase(), true])) as PluginConfig,",
  "});",
  "",
  "const activePlugins = computed(() =>",
  "  allPlugins.filter((plugin) => config.plugins[plugin.name.toLowerCase()] !== false)",
  ");",
  "",
  "function cmTheme() {",
  '  return theme.value === "dark" ? githubDark : githubLight;',
  "}",
  "",
  "function mardoraTheme() {",
  '  return theme.value === "dark" ? ThemeEnum.DARK : ThemeEnum.LIGHT;',
  "}",
  "```",
  "",
  "## 5. 创建 EditorView",
  "",
  "```ts",
  "async function uploader(file: File) {",
  "  // Demo 使用 blob URL；生产环境必须上传到后端或对象存储。",
  "  const url = URL.createObjectURL(file);",
  "  objectUrls.push(url);",
  "",
  "  return {",
  "    url,",
  "    name: file.name,",
  "    mimeType: file.type,",
  "  };",
  "}",
  "",
  "function createEditorView() {",
  "  if (!editorHost.value) return;",
  "",
  "  const updateListener = EditorView.updateListener.of((update) => {",
  "    if (!update.docChanged || internalUpdate) return;",
  "    content.value = update.state.doc.toString();",
  "  });",
  "",
  "  editorView.value = new EditorView({",
  "    parent: editorHost.value,",
  "    state: EditorState.create({",
  "      doc: content.value,",
  "      extensions: [",
  "        cmTheme(),",
  "        mardora({",
  "          theme: mardoraTheme(),",
  "          locale: config.locale,",
  "          baseStyles: config.editor.baseStyles,",
  "          plugins: activePlugins.value,",
  '          disableViewPlugin: mode.value === "code",',
  "          defaultKeybindings: config.editor.defaultKeybindings,",
  "          history: config.editor.history,",
  "          indentWithTab: config.editor.indentWithTab,",
  "          highlightActiveLine: config.editor.highlightActiveLine,",
  "          lineWrapping: config.editor.lineWrapping,",
  "          slashCommands: {",
  "            enabled: config.features.slashCommands,",
  "          },",
  "          selectionToolbar: {",
  "            enabled: config.features.selectionToolbar,",
  "          },",
  "          toc: {",
  '            enabled: mode.value === "live" && config.features.tableOfContents,',
  '            storageKey: "mardora-vue3:toc",',
  "            onTocChange: (items) => {",
  "              previewToc.value = items;",
  "            },",
  "          },",
  "          attachments: {",
  "            enabled: config.features.attachments,",
  "            uploader: config.features.attachments ? uploader : undefined,",
  "            enablePaste: config.features.pasteDropUploads,",
  "            enableDrop: config.features.pasteDropUploads,",
  "            accept: {",
  '              image: ["image/*"],',
  '              video: ["video/*"],',
  '              audio: ["audio/*"],',
  '              file: ["*/*"],',
  "            },",
  "          },",
  "          onNodesChange: (nextNodes) => {",
  "            nodes.value = nextNodes;",
  "          },",
  "        }),",
  "        updateListener,",
  "      ],",
  "    }),",
  "  });",
  "}",
  "```",
  "",
  "## 6. Preview 与输出模式",
  "",
  "```ts",
  "async function renderPreview() {",
  "  const syntaxTheme = cmTheme();",
  "",
  "  const htmlOutput = await preview(content.value, {",
  "    theme: mardoraTheme(),",
  "    plugins: activePlugins.value,",
  "    markdown: [],",
  "    syntaxTheme,",
  "    sanitize: config.preview.sanitize,",
  '    wrapperTag: "div",',
  '    wrapperClass: "mardora-preview vue3-preview",',
  "  });",
  "",
  "  const cssOutput = generateCSS({",
  "    theme: mardoraTheme(),",
  "    plugins: activePlugins.value,",
  '    wrapperClass: "mardora-preview",',
  "    includeBase: config.preview.includeBase,",
  "    syntaxTheme,",
  "  });",
  "",
  "  previewOutput.value = { html: htmlOutput, css: cssOutput };",
  "  previewToc.value = extractPreviewTocFromMarkdown(content.value);",
  "",
  "  await nextTick();",
  "",
  '  if (mode.value === "view") updatePreviewStyles();',
  '  if (mode.value === "output") createOutputViews();',
  "}",
  "",
  "function updatePreviewStyles() {",
  "  if (!previewHost.value) return;",
  "",
  "  if (!previewStyleElement.value) {",
  '    previewStyleElement.value = document.createElement("style");',
  "    previewHost.value.prepend(previewStyleElement.value);",
  "  }",
  "",
  "  previewStyleElement.value.textContent = previewOutput.value.css;",
  "}",
  "",
  "function createOutputViews() {",
  "  if (!htmlOutputHost.value || !cssOutputHost.value) return;",
  "",
  "  htmlView.value = new EditorView({",
  "    parent: htmlOutputHost.value,",
  "    state: EditorState.create({",
  "      doc: previewOutput.value.html,",
  "      extensions: [cmTheme(), html(), EditorView.lineWrapping, EditorState.readOnly.of(true)],",
  "    }),",
  "  });",
  "",
  "  cssView.value = new EditorView({",
  "    parent: cssOutputHost.value,",
  "    state: EditorState.create({",
  "      doc: previewOutput.value.css,",
  "      extensions: [cmTheme(), css(), EditorView.lineWrapping, EditorState.readOnly.of(true)],",
  "    }),",
  "  });",
  "}",
  "```",
  "",
  "## 7. 重建与销毁",
  "",
  "```ts",
  "async function rebuildForMode() {",
  "  await nextTick();",
  "  destroyViews();",
  "",
  '  if (mode.value === "view" || mode.value === "output") {',
  "    await renderPreview();",
  "    return;",
  "  }",
  "",
  "  createEditorView();",
  "}",
  "",
  "function destroyViews() {",
  "  editorView.value?.destroy();",
  "  htmlView.value?.destroy();",
  "  cssView.value?.destroy();",
  "  editorView.value = null;",
  "  htmlView.value = null;",
  "  cssView.value = null;",
  "",
  "  if (previewStyleElement.value) {",
  "    previewStyleElement.value.remove();",
  "    previewStyleElement.value = null;",
  "  }",
  "}",
  "",
  "watch([mode, theme, activePlugins], () => {",
  "  rebuildForMode();",
  "});",
  "",
  "watch(",
  "  config,",
  "  () => {",
  "    rebuildForMode();",
  "  },",
  "  { deep: true }",
  ");",
  "",
  "watch(content, (next) => {",
  "  if (!editorView.value || next === editorView.value.state.doc.toString()) return;",
  "",
  "  internalUpdate = true;",
  "  editorView.value.dispatch({",
  "    changes: {",
  "      from: 0,",
  "      to: editorView.value.state.doc.length,",
  "      insert: next,",
  "    },",
  "  });",
  "  internalUpdate = false;",
  "});",
  "",
  "onMounted(() => {",
  "  rebuildForMode();",
  "});",
  "",
  "onBeforeUnmount(() => {",
  "  destroyViews();",
  "",
  "  for (const url of objectUrls) {",
  "    URL.revokeObjectURL(url);",
  "  }",
  "  objectUrls.length = 0;",
  "});",
  "```",
  "",
  "## 8. API 表",
  "",
  "### 8.1 编辑器配置",
  "",
  "| 配置                       | 默认值           | Vue 3 建议                                                |",
  "| -------------------------- | ---------------- | --------------------------------------------------------- |",
  "| `theme`                    | `ThemeEnum.AUTO` | 和应用主题 ref 同步。                                     |",
  '| `locale`                   | `"zh-CN"`        | 由产品语言决定。                                          |',
  "| `baseStyles`               | `true`           | 初次接入保持开启。                                        |",
  "| `plugins`                  | `[]`             | 传 `activePlugins.value`。                                |",
  "| `disableViewPlugin`        | `false`          | 源码模式设为 `true`。                                     |",
  "| `defaultKeybindings`       | `true`           | 保持开启。                                                |",
  "| `history`                  | `true`           | 保持开启。                                                |",
  "| `indentWithTab`            | `true`           | 保持开启。                                                |",
  "| `highlightActiveLine`      | `true`           | 源码模式有效。                                            |",
  "| `lineWrapping`             | `true`           | 保持开启。                                                |",
  "| `slashCommands.enabled`    | `true`           | 用 feature toggle 控制。                                  |",
  "| `selectionToolbar.enabled` | `true`           | 用 feature toggle 控制。                                  |",
  "| `toc.enabled`              | `true`           | live 模式开启，预览用 `extractPreviewTocFromMarkdown()`。 |",
  "| `attachments.enabled`      | `false`          | 有 uploader 后开启。                                      |",
  "",
  "### 8.2 附件上传配置",
  "",
  "| 属性          | 默认值           | 说明                                           |",
  "| ------------- | ---------------- | ---------------------------------------------- |",
  "| `enabled`     | `false`          | 总开关。                                       |",
  "| `uploader`    | `undefined`      | 必须传入，未传时附件扩展不注册。               |",
  "| `enablePaste` | `true`           | 是否处理剪贴板文件。                           |",
  "| `enableDrop`  | `true`           | 是否处理拖拽文件。                             |",
  "| `accept`      | 类型侧默认 `*/*` | 按 `image/video/audio/file` 限制 MIME 或后缀。 |",
  "",
  "上传成功后，Mardora 会把 `image` 转成 Markdown 图片，把 `video/audio` 转成 HTML 标签，把 `file` 转成 Markdown 链接。存储、鉴权、病毒扫描、大小限制都属于业务后端职责。",
  "",
  "### 8.3 TOC 配置",
  "",
  "| 属性              | 默认值      | 说明                         |",
  "| ----------------- | ----------- | ---------------------------- |",
  "| `enabled`         | `true`      | 是否显示内置 TOC。           |",
  "| `minLevel`        | `2`         | 最小标题层级。               |",
  "| `maxLevel`        | `6`         | 最大标题层级。               |",
  "| `defaultExpanded` | `true`      | 默认展开。                   |",
  "| `defaultWidth`    | `240`       | 默认宽度。                   |",
  "| `minWidth`        | `180`       | 最小宽度，源码限制至少 120。 |",
  "| `maxWidth`        | `360`       | 最大宽度。                   |",
  "| `storageKey`      | `undefined` | 保存展开和宽度状态。         |",
  "",
  "## 9. 附件上传生产实现",
  "",
  "```ts",
  "async function productionUploader(file: File, context: MardoraAttachmentUploadContext) {",
  '  if (!["image", "video", "audio", "file"].includes(context.kind)) {',
  '    throw new Error("Unsupported attachment kind");',
  "  }",
  "",
  "  const form = new FormData();",
  '  form.append("file", file);',
  '  form.append("kind", context.kind);',
  '  form.append("source", context.source);',
  "",
  '  const response = await fetch("/api/uploads", {',
  '    method: "POST",',
  "    body: form,",
  "  });",
  "",
  "  if (!response.ok) {",
  '    throw new Error("Upload failed");',
  "  }",
  "",
  "  return response.json() as Promise<{",
  "    url: string;",
  "    name?: string;",
  "    title?: string;",
  "    mimeType?: string;",
  "  }>;",
  "}",
  "```",
  "",
  "## 10. 插件体系",
  "",
  "Vue 3 中自定义插件不需要 Composition API 包装。插件仍然是 Mardora 标准插件：",
  "",
  "| 方法                                    | 用途                       |",
  "| --------------------------------------- | -------------------------- |",
  "| `getExtensions()`                       | 添加 CodeMirror 扩展。     |",
  "| `getMarkdownConfig()`                   | 添加 Lezer Markdown 语法。 |",
  "| `getKeymap()`                           | 添加快捷键。               |",
  "| `buildDecorations(ctx)`                 | 添加编辑态 decoration。    |",
  "| `renderToHTML(node, children, ctx)`     | 添加 preview HTML。        |",
  "| `getPreviewStyles(theme, wrapperClass)` | 添加 preview CSS。         |",
  "",
  "如果自定义插件会创建资源或监听器，应在 `onViewReady()` 注册，在 `onUnregister()` 或 view destroy 路径清理。",
  "",
  "## 11. 验收清单",
  "",
  "- `mode` 切换不会留下旧 EditorView。",
  "- 输入正文不会触发频繁重建。",
  "- `preview()` 和 `generateCSS()` 使用同一组插件和主题。",
  "- 附件上传在 slash、paste、drop 三种来源都按预期工作。",
  "- 上传失败能被用户看见。",
  "- TOC 在编辑态和预览态都能跳转。",
  "- 卸载时 `EditorView.destroy()` 和 `URL.revokeObjectURL()` 已执行。",
  "- 默认文档和用户文档有明确持久化策略。",
].join("\n");

// playground/vue3-playground/src/data/md/react-guide.ts
export default [
  "# React 接入指南",
  "",
  "本文面向 React 项目，目标是接入一个与 Mardora React playground 同等质量的编辑器：支持富 Markdown 编辑、源码模式、预览模式、HTML/CSS 输出、插件开关、slash commands、附件上传、选区工具栏、主题切换、本地持久化和节点调试。",
  "",
  "React playground 使用 `@uiw/react-codemirror` 封装 CodeMirror 生命周期。你也可以手动创建 `EditorView`，但大多数 React 项目使用 `@uiw/react-codemirror` 会更直接。",
  "",
  "## 1. React 接入结论",
  "",
  "| 项目     | 建议                                                                      |",
  "| -------- | ------------------------------------------------------------------------- |",
  "| 接入方式 | 使用 `@uiw/react-codemirror` 渲染编辑器。                                 |",
  "| 状态同步 | React state 保存 Markdown 原文，`onChange` 更新当前文档。                 |",
  "| 扩展管理 | 用 `useMemo` 生成 Mardora extensions，避免每次输入重建。                  |",
  "| 预览     | 用 `useEffect` 在 view/output 模式下调用 `preview()` 和 `generateCSS()`。 |",
  "| 附件上传 | 用 `useCallback` 提供稳定 uploader。                                      |",
  "| 资源清理 | 在 `useEffect` cleanup 中释放 `blob:` URL。                               |",
  "",
  "## 2. 安装依赖",
  "",
  "```shell",
  "npm install mardora",
  "npm install @uiw/react-codemirror",
  "```",
  "",
  "下面的 HTML/CSS 输出面板示例会用到 `@codemirror/lang-html`、`@codemirror/lang-css` 和 `@uiw/codemirror-theme-github`；只有保留该面板时才需要按需安装。",
  "",
  "Next.js App Router 中，编辑器组件必须是 client component：",
  "",
  "```tsx",
  '"use client";',
  "```",
  "",
  "## 3. 类型与默认配置",
  "",
  "```tsx",
  'import { useCallback, useEffect, useMemo, useRef, useState } from "react";',
  'import CodeMirror, { ReactCodeMirrorRef } from "@uiw/react-codemirror";',
  'import { githubDark, githubLight } from "@uiw/codemirror-theme-github";',
  'import { html } from "@codemirror/lang-html";',
  'import { css } from "@codemirror/lang-css";',
  'import { EditorView, Extension, mardora, MardoraNode, MardoraPlugin, ThemeEnum } from "mardora/editor";',
  'import { allPlugins } from "mardora/plugins";',
  'import { generateCSS, preview } from "mardora/preview";',
  "",
  "type Content = {",
  "  id: string;",
  "  title: string;",
  "  content: string;",
  "};",
  "",
  'type Mode = "live" | "view" | "code" | "output";',
  "type PluginConfig = Record<string, boolean>;",
  "",
  "type PlaygroundConfig = {",
  "  editor: {",
  "    baseStyles: boolean;",
  "    defaultKeybindings: boolean;",
  "    history: boolean;",
  "    indentWithTab: boolean;",
  "    highlightActiveLine: boolean;",
  "    lineWrapping: boolean;",
  "  };",
  "  preview: {",
  "    includeBase: boolean;",
  "    sanitize: boolean;",
  "  };",
  "  features: {",
  "    slashCommands: boolean;",
  "    attachments: boolean;",
  "    pasteDropUploads: boolean;",
  "    selectionToolbar: boolean;",
  "    tableOfContents: boolean;",
  "  };",
  "  plugins: PluginConfig;",
  "};",
  "",
  "const defaultPluginConfig: PluginConfig = Object.fromEntries(",
  "  allPlugins.map((plugin) => [plugin.name.toLowerCase(), true])",
  ");",
  "",
  "const defaultConfig: PlaygroundConfig = {",
  "  editor: {",
  "    baseStyles: true,",
  "    defaultKeybindings: true,",
  "    history: true,",
  "    indentWithTab: true,",
  "    highlightActiveLine: true,",
  "    lineWrapping: true,",
  "  },",
  "  preview: {",
  "    includeBase: true,",
  "    sanitize: true,",
  "  },",
  "  features: {",
  "    slashCommands: true,",
  "    attachments: true,",
  "    pasteDropUploads: true,",
  "    selectionToolbar: true,",
  "    tableOfContents: true,",
  "  },",
  "  plugins: defaultPluginConfig,",
  "};",
  "```",
  "",
  "## 4. 默认文档和持久化",
  "",
  "```tsx",
  'const STORAGE_KEY = "mardora-playground-contents";',
  'const STORAGE_CURRENT_KEY = "mardora-playground-current";',
  'const STORAGE_VERSION_KEY = "mardora-playground-version";',
  "const STORAGE_VERSION = 2;",
  "",
  "const DEFAULT_CONTENTS: Content[] = [",
  '  { id: "project-introduction", title: "项目介绍", content: projectIntroduction },',
  '  { id: "vue2-guide", title: "Ve2 接入指南", content: vue2Guide },',
  '  { id: "vue3-guide", title: "Vue3 接入指南", content: vue3Guide },',
  '  { id: "react-guide", title: "React 接入指南", content: reactGuide },',
  "];",
  "",
  "const DEFAULT_CONTENT_IDS = new Set(DEFAULT_CONTENTS.map((content) => content.id));",
  "```",
  "",
  "| 字段                  | 作用               | 建议                                         |",
  "| --------------------- | ------------------ | -------------------------------------------- |",
  "| `STORAGE_VERSION`     | 默认文档版本。     | 默认文档标题或内容变化时递增。               |",
  "| `DEFAULT_CONTENT_IDS` | 识别系统默认文档。 | 版本升级时替换默认文档，保留用户文档。       |",
  "| `content`             | Markdown 原文。    | 生产系统保存它，不保存 EditorView 内部状态。 |",
  "",
  "## 5. 主组件状态",
  "",
  "```tsx",
  "export function MardoraReactEditor() {",
  "  const [contents, setContents] = useState<Content[]>(DEFAULT_CONTENTS);",
  "  const [currentContent, setCurrentContent] = useState(0);",
  '  const [mode, setMode] = useState<Mode>("live");',
  "  const [config, setConfig] = useState<PlaygroundConfig>(defaultConfig);",
  "  const [nodes, setNodes] = useState<MardoraNode[]>([]);",
  "  const [output, setOutput] = useState<{ html: string; css: string } | null>(null);",
  "",
  "  const editor = useRef<ReactCodeMirrorRef>(null);",
  "  const objectUrlsRef = useRef<string[]>([]);",
  "",
  '  const theme = "light";',
  '  const cmTheme = theme === "dark" ? githubDark : githubLight;',
  '  const mardoraTheme = theme === "dark" ? ThemeEnum.DARK : ThemeEnum.LIGHT;',
  "",
  "  const activePlugins = useMemo<MardoraPlugin[]>(() => {",
  "    return allPlugins.filter((plugin) => {",
  "      const name = plugin.name.toLowerCase();",
  "      return config.plugins[name] ?? true;",
  "    });",
  "  }, [config.plugins]);",
  "}",
  "```",
  "",
  "## 6. 附件上传",
  "",
  "```tsx",
  "const uploader = useCallback(async (file: File) => {",
  "  // Demo 可以用 blob URL；生产环境必须改成真实上传接口。",
  "  const url = URL.createObjectURL(file);",
  "  objectUrlsRef.current.push(url);",
  "",
  "  return {",
  "    url,",
  "    name: file.name,",
  "    mimeType: file.type,",
  "  };",
  "}, []);",
  "",
  "useEffect(() => {",
  "  return () => {",
  "    // 释放 demo 上传产生的 blob URL。",
  "    for (const url of objectUrlsRef.current) {",
  "      URL.revokeObjectURL(url);",
  "    }",
  "    objectUrlsRef.current = [];",
  "  };",
  "}, []);",
  "```",
  "",
  "### 6.1 附件上传 API 表",
  "",
  "| 属性                      | 默认值           | 说明                                                                            |",
  "| ------------------------- | ---------------- | ------------------------------------------------------------------------------- |",
  "| `attachments.enabled`     | `false`          | 是否启用附件能力。                                                              |",
  "| `attachments.uploader`    | `undefined`      | 实际上传函数；未提供时 paste/drop 扩展不会注册，slash media 命令使用 fallback。 |",
  "| `attachments.enablePaste` | `true`           | 是否处理剪贴板文件。                                                            |",
  "| `attachments.enableDrop`  | `true`           | 是否处理拖拽文件。                                                              |",
  "| `attachments.accept`      | 类型侧默认 `*/*` | 按 `image/video/audio/file` 限制 MIME 或后缀。                                  |",
  "",
  "### 6.2 Mardora 提供了什么",
  "",
  "| 阶段     | Mardora 行为                                               |",
  "| -------- | ---------------------------------------------------------- |",
  "| 文件来源 | 支持 slash 文件选择、粘贴、拖拽。                          |",
  "| 上传前   | 插入 `mardora-upload://task-id` 临时标记。                 |",
  "| 上传中   | 调用 `uploader(file, context)`。                           |",
  "| 上传成功 | 按附件类型替换为 Markdown 图片、音视频 HTML 或文件链接。   |",
  "| 上传失败 | 替换为 `[Upload failed: name](mardora-upload://task-id)`。 |",
  "",
  "Mardora 不提供对象存储、鉴权、文件扫描、断点续传、进度条或删除接口。需要这些能力时，业务侧应在 uploader 和自己的 UI 中实现。",
  "",
  "## 7. 生成 Mardora extensions",
  "",
  "```tsx",
  "const extensions = useMemo<Extension[]>(",
  "  () =>",
  "    mardora({",
  "      theme: mardoraTheme,",
  "      baseStyles: config.editor.baseStyles,",
  "      plugins: activePlugins,",
  '      disableViewPlugin: mode === "code",',
  "      defaultKeybindings: config.editor.defaultKeybindings,",
  "      history: config.editor.history,",
  "      indentWithTab: config.editor.indentWithTab,",
  "      highlightActiveLine: config.editor.highlightActiveLine,",
  "      lineWrapping: config.editor.lineWrapping,",
  "      slashCommands: {",
  "        enabled: config.features.slashCommands,",
  "      },",
  "      selectionToolbar: {",
  "        enabled: config.features.selectionToolbar,",
  "      },",
  "      toc: {",
  '        enabled: mode === "live" && config.features.tableOfContents,',
  '        storageKey: "mardora-react:toc",',
  "      },",
  "      attachments: {",
  "        enabled: config.features.attachments,",
  "        uploader: config.features.attachments ? uploader : undefined,",
  "        enablePaste: config.features.pasteDropUploads,",
  "        enableDrop: config.features.pasteDropUploads,",
  "        accept: {",
  '          image: ["image/*"],',
  '          video: ["video/*"],',
  '          audio: ["audio/*"],',
  '          file: ["*/*"],',
  "        },",
  "      },",
  "      onNodesChange: (nextNodes) => {",
  "        setNodes(nextNodes);",
  "      },",
  "    }),",
  "  [activePlugins, config.editor, config.features, mardoraTheme, mode, uploader]",
  ");",
  "```",
  "",
  "不要把当前 Markdown 文本放入这个 `useMemo` 依赖。正文变化应通过 `CodeMirror value/onChange` 同步，否则每次输入都会重建扩展。",
  "",
  "## 8. 渲染编辑、预览和输出",
  "",
  "```tsx",
  "const current = contents[currentContent];",
  "",
  "return (",
  '  <main className="mardora-react-shell">',
  '    {mode === "view" && output ? (',
  '      <article className="mardora-preview-host">',
  "        <style>{output.css}</style>",
  "        <div dangerouslySetInnerHTML={{ __html: output.html }} />",
  "      </article>",
  '    ) : mode === "output" && output ? (',
  '      <div className="mardora-output-grid">',
  "        <CodeMirror",
  "          value={output.html}",
  "          theme={cmTheme}",
  "          extensions={[html(), EditorView.lineWrapping, EditorView.editable.of(false)]}",
  "          editable={false}",
  "        />",
  "        <CodeMirror",
  "          value={output.css}",
  "          theme={cmTheme}",
  "          extensions={[css(), EditorView.lineWrapping, EditorView.editable.of(false)]}",
  "          editable={false}",
  "        />",
  "      </div>",
  "    ) : (",
  "      <CodeMirror",
  "        ref={editor}",
  "        value={current.content}",
  "        theme={cmTheme}",
  "        extensions={extensions}",
  "        basicSetup={false}",
  "        onChange={(value) => {",
  "          setContents((items) =>",
  "            items.map((item, index) => (index === currentContent ? { ...item, content: value } : item))",
  "          );",
  "        }}",
  "      />",
  "    )}",
  "  </main>",
  ");",
  "```",
  "",
  "`basicSetup={false}` 用于避免 `@uiw/react-codemirror` 默认扩展与 Mardora 组装的扩展重复。",
  "",
  "## 9. 生成预览输出",
  "",
  "```tsx",
  "useEffect(() => {",
  '  if (!["view", "output"].includes(mode)) return;',
  "",
  "  let cancelled = false;",
  "",
  "  (async () => {",
  '    const markdown = contents[currentContent]?.content || "";',
  "",
  "    const htmlOutput = await preview(markdown, {",
  "      theme: mardoraTheme,",
  "      plugins: activePlugins,",
  "      markdown: [],",
  "      syntaxTheme: cmTheme,",
  "      sanitize: config.preview.sanitize,",
  '      wrapperTag: "div",',
  '      wrapperClass: "mardora-preview",',
  "    });",
  "",
  "    const cssOutput = generateCSS({",
  "      theme: mardoraTheme,",
  "      plugins: activePlugins,",
  '      wrapperClass: "mardora-preview",',
  "      includeBase: config.preview.includeBase,",
  "      syntaxTheme: cmTheme,",
  "    });",
  "",
  "    if (!cancelled) {",
  "      setOutput({ html: htmlOutput, css: cssOutput });",
  "    }",
  "  })();",
  "",
  "  return () => {",
  "    cancelled = true;",
  "  };",
  "}, [activePlugins, cmTheme, config.preview, contents, currentContent, mardoraTheme, mode]);",
  "```",
  "",
  "| API                       | 默认值              | React 建议                        |",
  "| ------------------------- | ------------------- | --------------------------------- |",
  "| `preview.plugins`         | `[]`                | 使用 `activePlugins`。            |",
  "| `preview.sanitize`        | `true`              | 用户内容保持开启。                |",
  '| `preview.wrapperClass`    | `"mardora-preview"` | 和 CSS 生成保持一致。             |',
  "| `generateCSS.includeBase` | `true`              | 需要完全自定义 spacing 时再关闭。 |",
  "| `generateCSS.syntaxTheme` | `undefined`         | 使用当前 CodeMirror theme。       |",
  "",
  "## 10. Mardora 配置速查",
  "",
  "| 配置                       | 默认值           | React 建议                                |",
  "| -------------------------- | ---------------- | ----------------------------------------- |",
  "| `theme`                    | `ThemeEnum.AUTO` | 从主题状态映射为 `ThemeEnum.LIGHT/DARK`。 |",
  "| `baseStyles`               | `true`           | 初次接入保持开启。                        |",
  "| `plugins`                  | `[]`             | 传 `activePlugins`。                      |",
  '| `disableViewPlugin`        | `false`          | `mode === "code"` 时设为 `true`。         |',
  "| `defaultKeybindings`       | `true`           | 保持开启。                                |",
  "| `history`                  | `true`           | 保持开启。                                |",
  "| `indentWithTab`            | `true`           | 保持开启。                                |",
  "| `highlightActiveLine`      | `true`           | 源码模式有效。                            |",
  "| `lineWrapping`             | `true`           | 保持开启。                                |",
  "| `slashCommands.enabled`    | `true`           | feature toggle 控制。                     |",
  "| `selectionToolbar.enabled` | `true`           | feature toggle 控制。                     |",
  "| `toc.enabled`              | `true`           | live 模式开启。                           |",
  "| `attachments.enabled`      | `false`          | 有 uploader 后开启。                      |",
  "",
  "## 11. 插件体系",
  "",
  "React 接入不改变插件模型。自定义插件继承 `MardoraPlugin`：",
  "",
  "```tsx",
  'import type { DecorationContext } from "mardora/editor";',
  'import { MardoraPlugin } from "mardora/editor";',
  "",
  "class MentionPlugin extends MardoraPlugin {",
  '  readonly name = "mention";',
  '  readonly version = "1.0.0";',
  "",
  "  buildDecorations(ctx: DecorationContext): void {",
  "    // 在这里扫描 ctx.view.state.doc。",
  "    // 需要装饰时向 ctx.decorations 追加 Decoration.range(...)。",
  "  }",
  "}",
  "```",
  "",
  "| 插件方法              | 用途                     |",
  "| --------------------- | ------------------------ |",
  "| `getExtensions()`     | 添加 CodeMirror 扩展。   |",
  "| `getMarkdownConfig()` | 添加 Markdown 解析扩展。 |",
  "| `getKeymap()`         | 添加快捷键。             |",
  "| `buildDecorations()`  | 编辑态 decoration。      |",
  "| `renderToHTML()`      | preview HTML。           |",
  "| `getPreviewStyles()`  | preview CSS。            |",
  "",
  "## 12. 生产验收清单",
  "",
  "- `extensions` 不随每次输入重建。",
  "- `basicSetup={false}`，避免扩展重复。",
  "- 编辑、源码、预览、输出模式都能切换。",
  "- 附件上传成功、失败、超限和权限错误都有用户可见反馈。",
  "- slash media 命令和 paste/drop 复用同一个 uploader。",
  "- `preview()` 与 `generateCSS()` 使用同一组插件、主题和 syntax theme。",
  "- `blob:` URL 在组件卸载时释放。",
  "- 用户 Markdown 原文已保存到业务存储。",
].join("\n");
